- docs/decisions/0001-purpose-of-this-repo.rst
https://openedx.atlassian.net/browse/ENT-5229
> docs: Initial ADR describing the purpose and design of this service.

- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
> chore: update requirements to include braze-client

- enterprise_access/apps/api/exceptions.py
- enterprise_access/apps/api/filters.py
- enterprise_access/apps/api/serializers.py
- enterprise_access/apps/api/utils.py
- enterprise_access/apps/api/v1/tests/test_views.py
- enterprise_access/apps/api/v1/urls.py
- enterprise_access/apps/api/v1/views.py
- enterprise_access/apps/core/constants.py
- enterprise_access/apps/core/tests/factories.py
- enterprise_access/apps/subsidy_request/tests/factories.py
- enterprise_access/apps/subsidy_request/tests/test_admin.py
- enterprise_access/settings/base.py
- enterprise_access/urls.py
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
- test_utils/__init__.py
- set up get/post endpoints for license and coupon code requests
- set up edx-api-doc-tools
https://openedx.atlassian.net/browse/ENT-5306
> feat: add subsidy request endpoints

- Makefile
- docs/decisions/0001-purpose-of-this-repo.rst
- enterprise_access/apps/api/constants.py
- enterprise_access/apps/api/utils.py
- enterprise_access/apps/api/v1/tests/test_views.py
- enterprise_access/apps/api/v1/views.py
- enterprise_access/apps/api_client/base_oauth.py
- enterprise_access/apps/api_client/ecommerce_client.py
- enterprise_access/apps/api_client/license_manager_client.py
- enterprise_access/apps/api_client/tests/test_ecommerce_client.py
- enterprise_access/apps/api_client/tests/test_license_manager_client.py
- enterprise_access/apps/subsidy_request/models.py
- enterprise_access/apps/subsidy_request/utils.py
- enterprise_access/settings/base.py
- enterprise_access/settings/devstack.py
- enterprise_access/settings/test.py
- Adds approve and deny endpoints for licenses and coupons
- Hitting approval endpoint will hit license-manager/ecommerce to verify there are available licenses/coupons available
> Add approve and decline api endpoints

- enterprise_access/apps/core/models.py
- enterprise_access/apps/subsidy_request/models.py
Forgot to run make migrations.
> Revert "Add database indexes"

- enterprise_access/settings/base.py
https://docs.celeryq.dev/en/latest/django/first-steps-with-django.html#django-celery-results-using-the-django-orm-cache-as-a-result-backend
> fix: update celery result backend

- openedx.yaml
Updating release metadata ahead of Olive.
> build: this repo should be branched for Open edX releases

- enterprise_access/apps/api/serializers.py
- enterprise_access/apps/api/v1/views.py
- enterprise_access/apps/events/tests/test_utils.py
- enterprise_access/apps/events/utils.py
Description: This PR adds an event on the openedx event bus upon redemption of a subsidy
JIRA: https://2u-internal.atlassian.net/browse/ENT-6843
> feat: ENT-6843 dispatched event for subsidy redemption

- docs/decisions/0003-initial-api-specification.rst
- enterprise_access/apps/api/serializers.py
- enterprise_access/apps/api/v1/tests/test_views.py
- enterprise_access/apps/api/v1/urls.py
- enterprise_access/apps/api/v1/views.py
- enterprise_access/apps/subsidy_access_policy/constants.py
**GET list with group_uuid**
**GET list with group_uuid validation and POST form**
**Retrive/Delete/Patch**
> feat: Added CRUD API for subsidy policies

- enterprise_access/apps/api/v1/views.py
- enterprise_access/apps/events/utils.py
Description: This PR adds support for pushing access policy create/update events to the openedx event bus
JIRA: https://2u-internal.atlassian.net/browse/ENT-6843
> feat: ENT-6843 added events for access policy create-update

- scripts/README.rst
- scripts/lc2_generate_test_data/README.rst
- scripts/lc2_generate_test_data/lc2_generate_test_data.postman_collection.json
- scripts/lc2_generate_test_data/snowflake.sql
> docs: add LC2 test data postman collection and sample snowflake queries

- enterprise_access/apps/subsidy_access_policy/models.py
- enterprise_access/settings/base.py
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
Mix of 
https://2u-internal.atlassian.net/browse/ENT-6948 and
https://2u-internal.atlassian.net/browse/ENT-6947
I stated the version to use in settings so we can be a little flexible and switch to older versions without a deploy.
> feat: use v2 of subsidy list/create transactions api. ENT-6948

- enterprise_access/apps/api/serializers/__init__.py
- enterprise_access/apps/api/serializers/subsidy_access_policy.py
- enterprise_access/apps/api/serializers/subsidy_requests.py
https://2u-internal.atlassian.net/browse/ENT-6948
> refactor: split serializers into different files.

- enterprise_access/apps/api/v1/views/subsidy_access_policy.py
- provision-enterprise-access.sh
This automates a currently-manual step during devstack setup.
> [devstack] provision a SystemWideEnterpriseUserRoleAssignment

- scripts/lc2_generate_test_data/snowflake.sql
Correctly account for the state of Transactions and Reversals to enhance Subsidy balance calculation to calculate both "final" and "pending" balance.  Note this only impacts the demonstration/reference SQL query, not anything that actually gets run.
> docs: [snowflake] Take transaction state into consideration for balance calculation

- enterprise_access/settings/base.py
- enterprise_access/settings/utils.py
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
- add/configure https://github.com/dabapps/django-log-request-id middleware
- makes use of recent addition of `X-Request-ID` headers from SRE team
- adds `X-Request-ID` response header
- https://github.com/openedx/enterprise-subsidy/pull/92
> feat: enable x-request-id logging, replying

- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
- https://github.com/openedx/edx-rest-api-client/pull/270
- https://github.com/openedx/enterprise-access/pull/162
> feat: forward x-request-id headers

- enterprise_access/settings/utils.py
- i think i needed to also alter the syslog format
> feat: tweak request-id logging

- enterprise_access/settings/utils.py
trying one more theory, related to https://github.com/openedx/enterprise-access/pull/166
> fix: testing a theory

- enterprise_access/settings/utils.py
reverting the logger component until i can figure out why splunk is not picking up what i'm putting down.
- https://github.com/openedx/enterprise-access/pull/162
- https://github.com/openedx/enterprise-access/pull/164
- https://github.com/openedx/enterprise-access/pull/166
- https://github.com/openedx/enterprise-access/pull/167
> fix: reverting request-id logger changes

- enterprise_access/apps/subsidy_access_policy/content_metadata_api.py
Helps us get some visibility into the caching behavior around content metadata and catalog inclusion for policy can-redeem actions.
> feat: add some cache logging for catalog/content actions

- enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py
- enterprise_access/apps/api/v1/views/subsidy_access_policy.py
- enterprise_access/apps/subsidy_access_policy/models.py
- enterprise_access/apps/subsidy_access_policy/tests/test_models.py
- enterprise_access/apps/subsidy_access_policy/tests/test_utils.py
- enterprise_access/apps/subsidy_access_policy/utils.py
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
ENT-7204
All related PRs:
* https://github.com/openedx/enterprise-access/pull/191
* https://github.com/openedx/enterprise-subsidy/pull/113
* https://github.com/openedx/edx-enterprise-subsidy-client/pull/23
> feat: create and send an idempotency key to subsidy redeem()

- enterprise_access/apps/api/serializers/subsidy_access_policy.py
- enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py
- enterprise_access/apps/api/v1/views/subsidy_access_policy.py
Checks existing active policies with identical customer uuids, subsidy uuids, catalog uuids and access method and returns the policy if it exist, otherwise create a new policy.
pending tests
> feat: idempotent policies

- Makefile
- enterprise_access/apps/api/serializers/__init__.py
- enterprise_access/apps/api/serializers/subsidy_access_policy.py
- enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py
- enterprise_access/apps/api/v1/urls.py
- enterprise_access/apps/api/v1/views/__init__.py
- enterprise_access/apps/api/v1/views/subsidy_access_policy.py
- enterprise_access/apps/subsidy_access_policy/models.py
- enterprise_access/settings/base.py
> feat: add support for soft-deleting subsidy access policies

- enterprise_access/apps/subsidy_access_policy/models.py
- added some logging to observe/confirm behavior
- updated some documentation
> feat: cache logging

- enterprise_access/apps/subsidy_access_policy/models.py
- adding some logging to assert when the gate is disabled
> feat: more policy logging

- enterprise_access/apps/content_assignments/api.py
- enterprise_access/apps/content_assignments/tests/factories.py
- enterprise_access/apps/content_assignments/tests/test_api.py
- enterprise_access/apps/subsidy_access_policy/models.py
- enterprise_access/apps/subsidy_access_policy/tests/factories.py
- enterprise_access/apps/subsidy_access_policy/tests/test_models.py
https://2u-internal.atlassian.net/browse/ENT-7532
> feat: can_allocate() implementation for assignment-based policies. ENT-7532

- enterprise_access/apps/api_client/lms_client.py
- enterprise_access/apps/api_client/tests/test_lms_client.py
- enterprise_access/apps/api_client/tests/test_utils.py
> feat: add API client method to create pending enterprise learners

- enterprise_access/apps/subsidy_access_policy/admin.py
fixes an error for assignment-based policies when the "super admin" switch is enabled.
> fix: fix up admin for assignment-based policies

- enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py
- enterprise_access/apps/api/v1/views/subsidy_access_policy.py
- enterprise_access/apps/subsidy_access_policy/models.py
[ENT-7708](https://2u-internal.atlassian.net/browse/ENT-7708)
Unblocks [ENT-7741](https://2u-internal.atlassian.net/browse/ENT-7741).
> fix: ensure `credits_available` API returns proper policies

- docs/decisions/0013-assignment-actions-models.rst
- docs/decisions/README.rst
ADR describing motivation and outcome related to https://github.com/openedx/enterprise-access/pull/284
> docs: LearnerContentAssignmentActions ADR

- enterprise_access/apps/subsidy_access_policy/models.py
- enterprise_access/apps/subsidy_access_policy/tests/test_models.py
Noticed this bug in the context of listing policies for a particular customer within the provisioning tool.
> fix: handle HTTPErrors in SubsidyAccessPolicy.subsidy_record()

- enterprise_access/apps/subsidy_access_policy/admin.py
Quick little tool to help cut Postman out of the mix for testing e.g. new serializer method fields.  Adds a section to the policy details screen showing the serialized version of the policy record.
> feat: show API serialization of policy details from admin screen

- provision-enterprise-access.sh
- https://github.com/openedx/enterprise-subsidy/pull/165
- noticed some fixes leftover from the mysql8 upgrade
- [make the script safer](https://sipb.mit.edu/doc/safe-shell/)
- properly set colors
> fix: mysql8 provisioning scripts

- enterprise_access/apps/api/serializers/__init__.py
- enterprise_access/apps/api/serializers/content_assignments/assignment.py
- enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py
- enterprise_access/settings/devstack.py
This PR is a good template to understand how to add more metadata to content assignment `content_metadata`.
1. Find a sample course from enterprise-catalog to examine which content metadata fields are available. e.g. `https://enterprise-catalog.edx.org/api/v1/enterprise-catalogs/{{catalog_uuid}}/get_content_metadata/?format=json&content_keys=edX%2BDemoX`
2. Define a field in the `ContentMetadataForAssignmentSerializer` to pull your field(s) into the serialized response.
3. Update the `test_credits_available_endpoint_with_content_assignments` test function to ensure unit tests cover the addition of your new field(s)
4. Use Postman to test that the `credits_available` endpoint now pulls in your new field. `http://localhost:18270/api/v1/policy-redemption/credits_available/?enterprise_customer …
> feat: add course_type field to assignment content metadata serializer

- enterprise_access/apps/api/v1/tests/test_allocation_view.py
- enterprise_access/apps/api/v1/views/subsidy_access_policy.py
- enterprise_access/apps/content_assignments/api.py
- enterprise_access/apps/subsidy_access_policy/exceptions.py
- enterprise_access/apps/subsidy_access_policy/models.py
- enterprise_access/apps/subsidy_access_policy/tests/test_models.py
- enterprise_access/settings/base.py
- pylintrc
- pylintrc_tweaks
https://2u-internal.atlassian.net/browse/ENT-7793
> feat: validate requested allocation price

- enterprise_access/apps/content_assignments/management/commands/automatically_expire_assignments.py
- enterprise_access/apps/content_assignments/management/commands/tests/test_automatically_expire_assignments.py
**Description:** Convert the datetime string value into a datetime object for correct comparison.
> fix: datetime conversion

- enterprise_access/apps/api/serializers/content_assignments/assignment.py
- enterprise_access/apps/api/v1/tests/test_assignment_views.py
- enterprise_access/apps/content_assignments/tests/factories.py
Adding granularity of error messaging to use on the front end.
> feat: adding error messages to content assignments

- enterprise_access/apps/api/serializers/content_assignments/assignment.py
- enterprise_access/apps/api/v1/tests/test_assignment_views.py
Piggybacking [off this PR](https://github.com/openedx/enterprise-access/pull/338) but adding some tests in!
> fix: adding tests

- enterprise_access/apps/subsidy_access_policy/models.py
Add logging to the `can_allocate` endpoint
> feat: adding logging

- enterprise_access/apps/api/v1/tests/test_allocation_view.py
- enterprise_access/apps/subsidy_access_policy/models.py
- enterprise_access/apps/subsidy_access_policy/tests/test_models.py
- huddle with @macdiesel @pwnage101 @brobro10000 
- https://2u-internal.atlassian.net/browse/ENT-8177
> fix: fix allocation math

- docker-compose.yml
Removes the mysql 5.7 db container from devstack environment.
> build: no more mysql 5.7

- enterprise_access/apps/subsidy_access_policy/models.py
The request-cache utilization in `SubsidyAccessPolicy.subsidy_record()` is mature and stable enough now that we don't need to conditionally check if caching should be in use.  This commit removes it and the associated logging.
> refactor: subsidy_record() will always use cache

- docs/decisions/0016-policy-retirement.rst
> docs: Add ADR to describe field addition to support policy retirement

- enterprise_access/apps/content_assignments/management/commands/automatically_nudge_assignments.py
Updates syntax for gating logic for nudge assignment tasks
> fix: modifies gating logic for nudge assignments

- docs/decisions/0014-access-policy-grouping.rst
Description
ADR for the groups implementation into LC
https://2u-internal.atlassian.net/browse/ENT-8336
> feat: ADR for groups implementation

- docs/decisions/0018-access-policy-grouping.rst
branch wasn't rebased, didn't throw any conflicts ¯\_(ツ)_/¯
> fix: updating group adr with correct numbering

- enterprise_access/apps/api/filters/subsidy_request.py
fixes:
```
File "/edx/app/enterprise-access/enterprise_access/apps/api/filters/subsidy_request.py", line 85, in filter_queryset
return queryset.filter(
[...]
django.core.exceptions.ValidationError: ['   *    is not a valid UUID.']
```
> fix: check for * before filtering

- docs/decisions/0018-access-policy-grouping.rst
- enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py
- enterprise_access/apps/api_client/lms_client.py
- enterprise_access/apps/api_client/tests/test_lms_client.py
- enterprise_access/apps/subsidy_access_policy/models.py
- enterprise_access/apps/subsidy_access_policy/tests/factories.py
- enterprise_access/apps/subsidy_access_policy/tests/test_models.py
- test_utils/__init__.py
https://2u-internal.atlassian.net/browse/ENT-8416
> feat: update enterprise_contains_learner return value

- docs/decisions/0018-access-policy-grouping.rst
> feat: new context for groups adr on applies to all contexts situations

- enterprise_access/apps/subsidy_access_policy/admin.py
In order to test groups MVP - we need a manual way to add group policy associations
> feat: new policy group association admin

- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/test.txt
- requirements/validation.txt
Installs https://github.com/edx/braze-client/pull/24
https://openedx.atlassian.net/browse/ENT-8735
> feat: braze-client-0.2.3 | error response content in excs

- .github/PULL_REQUEST_TEMPLATE.md
Adding a PR template to this repository
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-8631)
> feat: adding PR template

- api-compact.yaml
- api.yaml
> feat: Added api.yaml file to expose public API's.

- enterprise_access/templates/subsidy_access_policy/admin/set_late_redemption.html
> docs: Update the text on the Set Late Redemption page (django admin actions)

- api-compact.yaml
- api.yaml
> fix: Change Assignment_UUIDs data type in public API

- enterprise_access/apps/content_assignments/management/commands/automatically_nudge_assignments.py
I can't get nudge emails to send in stage no matter what I've tried. Hopefully, adding logging to every branch of the funnel will help debug.
ENT-8789
> feat: assignment nudge emails - add logging to every branch

- api-compact.yaml
- api.yaml
https://2u-internal.atlassian.net/browse/ENT-8715
**Jira:**
ENT-XXXX
> feat: expose allocate assignment endpoint

- api-compact.yaml
- api.yaml
https://2u-internal.atlassian.net/browse/ENT-8717
**Jira:**
ENT-8717
> feat: expose assignment remind endpoint

- enterprise_access/apps/subsidy_access_policy/models.py
> fix: nudge emails should correspond do actual run enrolled

- api-compact.yaml
- api.yaml
> fix: fix API schema spec for allocate API

- api-compact.yaml
- api.yaml
> fix: update allocate endpoint schema

- api-compact.yaml
- api.yaml
403 Forbidden status to Subsidy Access Policy List API endpoint
**Jira:**
ENT-8996
> fix: added 403 Forbidden status to Subsidy Access Policy List API endpoint

- api-compact.yaml
- api.yaml
Added request parameters for the `subsidyAccessPolicies` endpoint
**Jira:**
ENT-8996
> feat: added request parameters for `subsidyAccessPolicies` endpoint

- enterprise_access/apps/enterprise_groups/tasks.py
Adds debugging log lines for `send_group_reminder_emails`
**Jira:**
ENT-9084
https://2u-internal.atlassian.net/browse/ENT-9084
> chore: add debugging lines

- enterprise_access/apps/subsidy_access_policy/models.py
> fix: isort lint

- enterprise_access/apps/api/serializers/subsidy_access_policy.py
- enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py
Update credits available API response to include group association.
**Jira:**
[ENT-9010](https://2u-internal.atlassian.net/browse/ENT-9010)
> feat: update credits available endpoint to include group association

- enterprise_access/settings/base.py
- enterprise_access/settings/devstack.py
all the small things at this point...
> fix: install openedx-events in base settings

- enterprise_access/apps/subsidy_access_policy/constants.py
- enterprise_access/apps/subsidy_access_policy/models.py
- enterprise_access/apps/subsidy_access_policy/tests/test_models.py
ENT-9222
Fixes https://2u-internal.atlassian.net/browse/ENT-9216
> fix: expired and reversed assignments should not be redeemable

- enterprise_access/apps/api/v1/tests/test_allocation_view.py
- enterprise_access/apps/content_assignments/api.py
- enterprise_access/apps/content_assignments/tests/test_api.py
The assignment *expiration* logic modifies the email field of the assignment (but not the lms_user_id). Prior to this change, when we look for existing assignments during allocation, we checked only by email. With this change, we now also check for existing, re-allocatable, assignments by lms_user_id.
This commit also fixes a bug where the "*_at" datetime fields weren't having a null value persisted on them during reallocation.
https://2u-internal.atlassian.net/browse/ENT-9122
> fix: allocation identifies learners by either email or lms_user_id

- enterprise_access/apps/content_assignments/models.py
Manual testing revealed a bug in https://github.com/openedx/enterprise-access/pull/516
This PR fixes the bug.
**Jira:**
ENT-9245
> fix: we still need coalesce as a default when there is no last reminder

- enterprise_access/templates/subsidy_access_policy/admin/deposit_funds.html
> docs: better help message in Deposit Funds action

- docs/decisions/0023-spend-limits-constraint.rst
- docs/decisions/README.rst
Based on [post merge feedback](https://github.com/openedx/enterprise-access/pull/523), updating the text
**Jira:**
ENT-XXXX
> fix: Update spend-limit constraint ADR

- api-compact.yaml
- api.yaml
Published Content assignment list endpoint
**Jira:**
ENT-8983
> feat: publish content assignment list endpoint

- api-compact.yaml
- api.yaml
Removed redundant descriptions from endpoint parameters. which was causing the Swagger server to fail.
**Jira:**
ENT-8983
> refactor: Remove redundant descriptions from endpoint parameters.

- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
Installs https://github.com/openedx/edx-rbac/pull/317
**Jira:**
ENT-9379
> feat: edx-rbac 1.10.0 to ignore invalid JWT cookies instead of raise

- tox.ini
https://tox.wiki/en/4.11.3/upgrading.html#changed-ini-rules
> TOX 40 updates.

- enterprise_access/apps/api_client/enterprise_catalog_client.py
- enterprise_access/apps/api_client/tests/test_enterprise_catalog_client.py
> feat: Update catalog API client to use v2 endpoints

- enterprise_access/apps/api/v1/urls.py
- enterprise_access/apps/api/v1/views/__init__.py
- enterprise_access/apps/api/v1/views/bffs/common.py
- enterprise_access/apps/api/v1/views/bffs/learner_portal.py
- enterprise_access/apps/api_client/tests/test_utils.py
- enterprise_access/apps/bffs/context.py
- enterprise_access/apps/bffs/handlers.py
- enterprise_access/apps/bffs/mixins.py
- enterprise_access/apps/bffs/response_builder.py
- enterprise_access/apps/bffs/serializers.py
- enterprise_access/apps/bffs/tests/test_handlers.py
**Jira:**
[ENT-9639](https://2u-internal.atlassian.net/browse/ENT-9639)
Wires up the BFF handlers, context, and response builders within LearnerPortalBFFViewSet.
**Note: Tests deferred for another fast-follow PR; prioritizing getting callable API to unblock API integration while tests and remaining functionality in the BFF API is implemented.**
Example request/response:
http://localhost:18270/api/v1/bffs/learner/dashboard/?enterprise_customer_uuid=7ad8cdb9-352c-4b71-bcf1-3015103cca1f
```json
{
"enterprise_customer_user_subsidies": {
"subscriptions": {
"customer_agreement": {
"uuid": "9571c2d9-d562-49e2-8f2e-2eaa92f07a84",
"available_subscription_catalogs": [
"f09ff39b-f456-4a03-b53b-44cd70f52108"
],
"default_enterprise_catalog_uuid": …
```
> feat: adds LearnerPortalBFFViewSet

- README.rst
"Dummy" commit to force a deployment.
**Jira:**
ENT-9894
> docs: fix typo

- enterprise_access/apps/content_assignments/tasks.py
- enterprise_access/apps/content_assignments/utils.py
> temp: add logs for debugging Braze emails campaign

- enterprise_access/apps/content_assignments/tasks.py
- enterprise_access/apps/content_assignments/tests/test_tasks.py
- enterprise_access/apps/content_assignments/tests/test_utils.py
- enterprise_access/utils.py
> fix: use course-run specific metadata

- README.rst
Quick readme change to trigger a new deployment artifact.
> docs: fix grammar

- enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py
- enterprise_access/apps/api/v1/views/subsidy_access_policy.py
Previous behavior before we required a non-null list_price was to return 200 response with reason = "content_not_in_catalog" if the content key was totally fake.  Now that we are no longer tolerant of NOT including the price in the response, we must return some sort of non-200 response.
Before this PR, the can-redeem endpoint would return 500.  This fixes the response to return 422 Unprocessable to at least indicate that the requester did something wrong.
> fix: [can-redeem] bogus content should not throw 500 response

- enterprise_access/apps/api_client/lms_client.py
- enterprise_access/apps/api_client/tests/test_lms_client.py
Adds some LmsApiClient() methods to fetch/create enterprise catalogs.
**Jira:**
ENT-9995
> feat: add client fetch/create catalog methods

- enterprise_access/apps/subsidy_access_policy/admin/__init__.py
- enterprise_access/apps/subsidy_request/admin.py
Register the `LearnerCreditRequestConfiguration` and `LearnerCreditRequest` model in admin. 
**Jira:**
ENT-10292
> feat: Register Learner Credit Request models in admin

- enterprise_access/apps/api/v1/tests/test_bff_views.py
- enterprise_access/apps/bffs/response_builder.py
- enterprise_access/apps/bffs/serializers.py
- enterprise_access/apps/subsidy_access_policy/models.py
> feat: Added that enterprise has any policy with bnr_enabled.

- enterprise_access/apps/api/serializers/subsidy_access_policy.py
Modify `credits_available` endpoint to include requested and approved bnr requests.
Sample Response: 
```json
HTTP 200 OK
Allow: GET
Content-Type: application/json
Vary: Accept
[
{
"uuid": "a12d4d9b-3d3b-4e5a-902d-a36d18a3fc82",
"policy_redemption_url": "http://localhost:18270/api/v1/policy-redemption/a12d4d9b-3d3b-4e5a-902d-a36d18a3fc82/redeem/",
"is_late_redemption_allowed": false,
"remaining_balance_per_user": 100,
"remaining_balance": 1000000,
"subsidy_expiration_date": "2027-10-30T14:50:31Z",
"learner_content_assignments": [],
"learner_requests": [
{
"uuid": "28ead042-c65c-4c7d-881f-1b7f90a89b3e",
"lms_user_id": 3,
"email": "[edx@example.com](mailto:edx@example.com)",
"course_id": "some_course_id",
"course_title": null,
"course_partners": null, …
```
> feat: added bnr requested courses in credits_available endpoint

- enterprise_access/apps/api/serializers/__init__.py
- enterprise_access/apps/api/serializers/customer_billing.py
- enterprise_access/apps/api/v1/urls.py
- enterprise_access/apps/api/v1/views/__init__.py
- enterprise_access/apps/api/v1/views/customer_billing.py
- enterprise_access/apps/core/constants.py
- enterprise_access/apps/core/rules.py
- enterprise_access/settings/base.py
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
- scripts/stripe_poc_setup.py
> feat: Initial Stripe Integration for SSP (proof-of-concept)

- enterprise_access/apps/subsidy_request/admin.py
Allow the admin to link the learner credit request config with learner credit request
**Jira:**
ENT-XXXX
> feat: Allow the admin to link LC request config with LC request.

- README.rst
I mostly just want a new revision to trigger a build pipeline with.
> docs: phrasing

- enterprise_access/apps/api/v1/views/browse_and_request.py
Made learner credit requests searchable using Course title and learner's email.
**Jira:**
[ENT-10349](https://2u-internal.atlassian.net/browse/ENT-10349)
> feat: made learner credit requests searchable

- enterprise_access/apps/subsidy_request/admin.py
> fix: made course_price field editable in LearnerCreditRequestAdmin

- enterprise_access/apps/subsidy_access_policy/models.py
- enterprise_access/apps/subsidy_access_policy/tests/test_models.py
Added new mixin to support redeem and can_redeem for BNR
**Jira:**
ENT-10327
> feat: Added new mixin to support redeem and can_redeem for BNR

- enterprise_access/apps/api/v1/views/subsidy_access_policy.py
> fix: Return 200 response except 404

- enterprise_access/apps/api_client/lms_client.py
- enterprise_access/apps/api_client/tests/test_lms_client.py
https://2u-internal.atlassian.net/browse/ENT-10581
We’re using GET endpoints to fetch any existing admins for a given admin email address to provision, but we’re not yet traversing the pagination of results. That means we can get false negatives before trying to create a pending admin record that already exists, resulting in an error.
> fix: handle paginated pending admin results

- enterprise_access/apps/bffs/mixins.py
> chore: add logs for debugging ENT-10561

- enterprise_access/apps/api/v1/tests/test_browse_and_request_views.py
- enterprise_access/apps/api/v1/views/browse_and_request.py
> chore: add action logging on LearnerCreditRequest creation

- docs/decisions/0029-self-service-purchasing-BFF.rst
> docs: Add ADR for Self-Service Purchasing BFF Endpoints

- enterprise_access/apps/content_assignments/api.py
- enterprise_access/apps/content_assignments/tests/test_api.py
In `expire_assignment` check if there is a credit request and expire it if it exists.
**Jira:**
[ENT-10570](https://2u-internal.atlassian.net/browse/ENT-10570)
> ENT-10570 Expire credit requests when an assignment expires

- enterprise_access/apps/subsidy_request/admin.py
> fix: bad gateway issue on learner credit requests table

- enterprise_access/apps/subsidy_request/constants.py
> fix: learner was not able to re-request a cancelled or declined course

- enterprise_access/apps/api/v1/tests/test_browse_and_request_views.py
- enterprise_access/apps/api/v1/views/browse_and_request.py
- enterprise_access/apps/content_assignments/api.py
- enterprise_access/apps/subsidy_request/constants.py
**Jira:**
https://2u-internal.atlassian.net/browse/ENT-10709
> fix: reuse existing request and assignment for re-request

- enterprise_access/apps/api/filters/__init__.py
- enterprise_access/apps/api/filters/subsidy_request.py
- enterprise_access/apps/api/v1/views/browse_and_request.py
Added filters to support filtering based on `policy_uuid`.
**Jira:**
ENT-XXXX
> feat: add policy filter for learner credit requests

- enterprise_access/apps/api/v1/tests/test_checkout_bff_views.py
- enterprise_access/apps/api/v1/views/bffs/checkout.py
- enterprise_access/apps/api_client/lms_client.py
- enterprise_access/apps/bffs/checkout/context.py
- enterprise_access/apps/bffs/checkout/handlers.py
- enterprise_access/apps/bffs/checkout/response_builder.py
- enterprise_access/apps/bffs/checkout/serializers.py
- enterprise_access/apps/bffs/tests/test_checkout_handlers.py
- enterprise_access/apps/bffs/tests/test_checkout_response_builder.py
- enterprise_access/apps/customer_billing/api.py
- enterprise_access/apps/customer_billing/constants.py
https://2u-internal.atlassian.net/browse/ENT-10630
Sample authenticated request (you can also test it without providing the auth header):
```
curl --location 'http://localhost:18270/api/v1/bffs/checkout/validation/' \
--header 'Authorization: JWT [my-jwt]' \
--header 'Content-Type: application/json' \
--data-raw '{
"admin_email": "edx@example.com",
"company_name": "Pied Piper",
"enterprise_slug": "pied-piper",
"full_name": "",
"quantity": 2,
"stripe_price_id": "1234"
}'
```
sample response:
```
{
"validation_decisions": {
"company_name": {
"error_code": "existing_enterprise_customer",
"developer_message": "An enterprise customer with this name already exists."
},
"enterprise_slug": {
"error_code": "existing_enterprise_customer",
"developer_message": "The slug conflicts with an existing …
```
> feat: checkout validation bff endpoint

- enterprise_access/apps/subsidy_access_policy/models.py
JIRA -> [ENT-10735](https://2u-internal.atlassian.net/browse/ENT-10735)
**Jira:**
ENT-XXXX
> fix: request state when redemption failure occur

- enterprise_access/apps/customer_billing/api.py
- enterprise_access/apps/customer_billing/stripe_api.py
- enterprise_access/apps/customer_billing/tests/test_api.py
Small refactor to prep for future additional functions to fetch stripe data.
**Jira:**
ENT-10714
> refactor: move stuff into stripe_api.py

- enterprise_access/apps/provisioning/docs/overview.rst
Doc walking through the provisioning flow, how it implements the workflow pattern, how it integrates with our REST API layer, and utilizes idempotent functions to call downstream APIs.
> docs: provisioning overview doc

- enterprise_access/apps/api/v1/tests/test_browse_and_request_views.py
- enterprise_access/apps/api/v1/views/browse_and_request.py
- enterprise_access/apps/content_assignments/tasks.py
- enterprise_access/apps/subsidy_request/tasks.py
Description:
Modified the existing email tasks for cancel and decline to use separate celery tasks instead of shared utility. Also added a base class to handle error action for email tasks.
Jira:
[ENT-10373](https://2u-internal.atlassian.net/browse/ENT-10737)
> feat: add logging for failed email tasks for bnr

- docs/decisions/0031-replace-EnterpriseSlugReservation-with-CheckoutIntent.rst
- enterprise_access/apps/api/serializers/__init__.py
- enterprise_access/apps/api/serializers/customer_billing.py
- enterprise_access/apps/api/v1/tests/test_checkout_intent_views.py
- enterprise_access/apps/api/v1/views/customer_billing.py
- enterprise_access/apps/content_assignments/tests/test_tasks.py
- enterprise_access/apps/customer_billing/models.py
> feat: allow creation of CheckoutIntents via REST API

- .github/workflows/ci.yml
Try splitting lint into a discrete workflow.
> build: split up CI workflows

- docs/architecture-overview.rst
> docs: add arch overview doc

- enterprise_access/apps/api/serializers/customer_billing.py
- enterprise_access/apps/api/v1/tests/test_checkout_intent_views.py
> fix: actually update REST layer to make slug/name optional
