openedx/enterprise-access

enterprise_access/apps/api/exceptions.py, enterprise_access/apps/api/tasks.py, enterprise_access/apps/api/tests/test_tasks.py, enterprise_access/apps/api/v1/tests/test_views.py, enterprise_access/apps/api/v1/views.py, enterprise_access/apps/api_client/lms_client.py, enterprise_access/apps/api_client/tests/test_lms_client.py, enterprise_access/tasks.py
- fix sending the wrong slug to braze, removed _get_enterprise_learner_data since we don't need this anymore
- refactor task for sending emails, it's not safe to retry a task that sends emails in a loop
- rename variables for clarity
=> fix: send correct enterprise slug to braze, make notification task retry safe

enterprise_access/apps/api/tasks.py, enterprise_access/apps/api/tests/test_tasks.py, enterprise_access/apps/subsidy_request/management/commands/tests/test_send_admins_email_with_new_requests.py, enterprise_access/apps/subsidy_request/tasks.py
Lowercase emails before calling send_campaign_message because it's case-sensitive. Braze guild to discuss always lowercasing emails in the client sometime in the future.
=> fix: lower case email before sending to braze

enterprise_access/apps/api/tasks.py, enterprise_access/apps/api/tests/test_tasks.py, enterprise_access/apps/subsidy_request/management/commands/tests/test_send_admins_email_with_new_requests.py, enterprise_access/apps/subsidy_request/tasks.py
https://openedx.atlassian.net/browse/ENT-5648
- send contact_admin_link to braze so that the administrator button works in the request declined email
=> feat: add contact admin link to decline email

enterprise_access/apps/api/tasks.py, enterprise_access/apps/api/tests/test_tasks.py, enterprise_access/apps/api/v1/tests/test_views.py, enterprise_access/apps/api/v1/views.py, enterprise_access/apps/api_client/lms_client.py, enterprise_access/apps/api_client/tests/test_lms_client.py
https://openedx.atlassian.net/browse/ENT-5619
- allow admins to remove learners from an enterprise while declining a subsidy request
=> feat: allow admins to unlink learners when declining a request

docker-compose.yml
Putting together a branch that supports Apple M1 macs. Hopefully backwards compatible with Intel macs but reserving the right to make breaking changes.
Also depends on https://github.com/openedx/devstack/pull/920.
Follow the [README](https://github.com/edx/enterprise-access#quick-setup) to setup the IDA.
=> feat: apple silicon m1 support

Dockerfile
Necessary for Apple M1 Silicon chip support.
```bash
make dev.down
make docker_build
make dev.up
make app-shell
make requirements
which pytest # this should return its installed path
```
=> build: explicitly install librdkafka in Dockerfile

docker-compose.yml
- help avoid migration issues
- leaves existing volumns untouched
- https://github.com/openedx/license-manager/pull/421
- https://github.com/openedx/enterprise-catalog/pull/447
=> build: use a version-named mysql volume for mysql8

.gitignore, Dockerfile, Makefile, docker-compose.yml
* Install `dev.txt` dependencies as part of a docker `devstack` build stage.
* Spit out distinct tagged images built against the `devstack` docker target.
* Run these images in docker-compose.yml
* modify `dev.up.build` to run `docker_build` first, so we're always running consistent, tagged app/worker images in dev environments.
* bonus: add backup/restore make targets for the DB container.
=> build: install dev requirements during build

enterprise_access/apps/events/data.py, enterprise_access/apps/events/signals.py
This is no longer planned as part of the event bus work, although it's probably still a good idea.
=> docs: Remove "event bus" from TODO comments

docs/testing.rst, pytest.local.ini
Does what the docs say, allow us to do this sort of thing now:
```
```
To generate targeted code coverage reports, e.g.:
```
---------- coverage: platform linux, python 3.8.10-final-0 -----------
Name                                        Stmts   Miss Branch BrPart  Cover   Missing
---------------------------------------------------------------------------------------
enterprise_access/apps/events/__init__.py       0      0      0      0   100%
enterprise_access/apps/events/apps.py           8      0      2      0   100%
enterprise_access/apps/events/data.py          55     16     10      0    72%   37-45, 68, 72, 100-111
enterprise_access/apps/events/signals.py        4      4      0      0     0%   5-18
enterprise_access/apps/events/utils.py         47     32     16      0    27% …
```
=> build: make local pytest coverage reporting on a code subset easier

.gitignore, enterprise_access/settings/base.py, enterprise_access/urls.py, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
__Jira Ticket:__ [ENT-6698](https://2u-internal.atlassian.net/browse/ENT-6698)
__Description:__
We need to expose the Open API schema for [enterprise-access](https://github.com/edx/enterprise-access) service so that is is accessible publicly. Sample implementation is available at the PR [prototype: drf-spectacular by iloveagent57 · Pull Request #89 · openedx/enterprise-access](https://github.com/openedx/enterprise-access/pull/89/commits)  make sure to use the changes with commit 1711195c68ae16ba906f86ac691660e7861c7934. 
**Acceptance Criteria:**
1. A public endpoint is available to access OpenAPI V3 Schema .
=> feat: Added URL definitions to expose OpenAPI schema.

enterprise_access/apps/events/apps.py, enterprise_access/apps/events/data.py, enterprise_access/apps/events/signals.py, enterprise_access/apps/events/tests/test_data.py, enterprise_access/apps/events/tests/test_utils.py, enterprise_access/apps/events/utils.py, enterprise_access/settings/base.py, enterprise_access/settings/devstack.py, enterprise_access/settings/test.py
__Jira Ticket:__ [ENT-6754](https://2u-internal.atlassian.net/browse/ENT-6754)
__Description:__
This PR adds mechanism for sending policy related events to event bus for anyone who wants to subscribe to these events and perform some operation.
**Acceptance Criteria:**
1. Kafka topics are created for policy created, policy updated and policy deleted events.
2. Avro Serializers are created for policy created, policy updated and policy deleted events.
3. Utility methods are created for policy created, policy updated and policy deleted events
4. Events are fired on when policy is created, updated or deleted.
=> feat: Added enterprise access events firing logic.

.gitignore, Dockerfile, codecov.yml, docker-compose.yml, docs/decisions/0006-api-specification-for-enterprise-mfes.rst
Adds a new ADR 0006 to describe 2 new endpoints in `enterprise-access/policy`:
1. `/api/v1/enterprise-customer/<enterprise_customer_uuid>/policy/can_redeem/`
2. `/api/v1/enterprise-customer/<enterprise_customer_uuid>/policy/<policy_uuid>/redemptions/<redemption_uuid>/`
[ADR Formatted Preview](https://github.com/openedx/enterprise-access/blob/cfcf8aa33534f17ddd84f0962390df68c6407a7f/docs/decisions/0006-api-specification-for-enterprise-mfes.rst)
**Tickets**
* [ENT-6921](https://2u-internal.atlassian.net/browse/ENT-6921)
* [ENT-6923](https://2u-internal.atlassian.net/browse/ENT-6923)
=> fix: update Dockerfile and docker-compose.yml, add api spec for MFEs

enterprise_access/apps/api/serializers.py, enterprise_access/apps/api/v1/tests/test_views.py, enterprise_access/apps/api/v1/views.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/test_models.py
The response of this endpoint determines whether the enroll button is shown, and contains business logic to decide which access policy should be used.
ENT-6854
=> feat: implement can_redeem endpoint

enterprise_access/apps/api/serializers.py, enterprise_access/apps/api/v1/tests/test_views.py, enterprise_access/settings/base.py, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
=> fix: policy_redemption_url should be a full URI

enterprise_access/apps/api/v1/views.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/factories.py, enterprise_access/apps/subsidy_access_policy/tests/test_models.py
The `subsidy-access-policy` app considers inactive (i.e., `active=False`) policies as redeemable. For example, calling the `http://localhost:18270/api/v1/policy/enterprise-customer/a067aacd-667d-4bd6-81e2-e332ef5ca1cd/can-redeem/?content_key=course-v1%3AedX%2BS2023%2B1T2023` endpoint, which has a policy marked as `active=False` that is otherwise redeemable, returns the inactive policy, which is not correct given `active=False`.
To fix this, we first check the generic `can_redeem` defined in the extended `SubsidyAccessPolicy` model before checking the policy-specific `can_redeem` business rules.
This ensures policies with `active=False` don't attempt to validate their own business (i.e., having to make API calls to `enterprise-subsidy`, etc.) if the policy isn't active to begin with.
=> fix: account for active flag on redeemable policies

docs/decisions/0008-additional-redemption-metadata.rst, enterprise_access/apps/api/serializers.py, enterprise_access/apps/api/v1/tests/test_views.py, enterprise_access/apps/api/v1/views.py, enterprise_access/apps/subsidy_access_policy/models.py, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
- This PR contains an ADR and the start of what modifications would be required to enact it.
- This ADR intends to outline modifications to existing API endpoint(s) such that MFEs can pass additional metadata into the redemption flow. This extension was devised to support required GEAG meatadata such as DOB and terms acceptance dates.
- if folks generally vibe with this, I will flesh out the PR to include a full implementation
- https://github.com/openedx/edx-enterprise-subsidy-client/pull/15
=> feat: redemption metadata

Makefile, enterprise_access/apps/api/serializers.py, enterprise_access/apps/api/v1/tests/test_views.py, enterprise_access/apps/api/v1/views.py, enterprise_access/apps/subsidy_access_policy/models.py, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
The subsidy access policy APIs should accept `lms_user_id` as a request parameter instead of `learner_id`.
Also, standardize the names of the request/response serializers used in the policy views.
Note: this PR is a breaking change to the REST API.
ENT-6988
Related PRs:
* https://github.com/openedx/enterprise-subsidy/pull/62
* https://github.com/openedx/edx-enterprise-subsidy-client/pull/16
=> refactor: rename `learner_id` -> `lms_user_id`

enterprise_access/apps/api/serializers.py, enterprise_access/apps/api/v1/views/browse_and_request.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py, enterprise_access/urls.py
It's spec-tac-u-lahhh!
To test:
- checkout this branch
- make sure devserver reloads
- Visit http://localhost:18270/api-docs/ (swagger docs at existing route, but powered by drf-spec now, so some things work a little nicer)
- Visit http://localhost:18270/api/schema/redoc/, observe the glory
I've tidy-d up the `can_redeem` docstring for now to render a little cleaner - it'll need some follow-up work to get its complicated/nested response serialization represented with a serializer class.
=> feat: lay down some drf-spec basics. ENT-6948

enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py, enterprise_access/apps/subsidy_access_policy/constants.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/test_models.py
* Uses a unique reason slug as the `reason` attribute.
* Generates a `user_message` for each reason based on the reason slug.
* The UI (learner portal MFE course page) will use the `user_message` for display in the below screenshots.
Related PRs:
* https://github.com/openedx/frontend-app-learner-portal-enterprise/pull/732
Sample response payload:
```json
[{
"content_key": "course-v1:edX+CTL.SC2x+1T2023a",
"redemptions": [],
"has_successful_redemption": false,
"redeemable_subsidy_access_policy": null,
"can_redeem": false,
"reasons": [{
"reason": "learner_max_spend_reached",
"user_message": "You can't enroll right now because of limits set by your organization.",
"metadata": {
"enterprise_administrators": [{
"email": "edx@example.com",
"lms_user_id": 3
}]
},
"policy_uuids": [ …
```
=> feat: use reason slugs and add `user_message` field in `can-redeem` response

enterprise_access/apps/api/serializers/__init__.py, enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py, enterprise_access/apps/subsidy_access_policy/models.py
This also bundles other improvements:
* output serializers are defined for the can_redeem endpoint, enabling much higher quality redoc pages
* added a ContentKeyField to replace the ValidateContentKeyMixin which was harder to use and overly complicated.
ENT-7137
=> feat: add `list_price` to response of can_redeem

enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/utils.py
Current implementation assumes the upstream `content_price` from subsidy will be a string like `"299.00"`; however, the `content_metadata` [API endpoint](https://enterprise-subsidy.edx.org/api/schema/redoc/#tag/api/operation/api_v1_content_metadata_retrieve) in subsidy returns USD cents like `29900`.
This PR updates the `list_price` API field in enterprise-access's `can-redeem` API response to return the correct denominations of USD and USD cents, e.g.:
```json
[{
"list_price": {
"usd": 299,
"usd_cents": 29900
}
}]
```
instead of the current state of saying the course is $29,900 USD:
```json
[{
"list_price": {
"usd": 29900,
"usd_cents": 2990000
}
}]
```
=> fix: list price on `can-redeem` API endpoint

enterprise_access/apps/api/v1/views/subsidy_access_policy.py, enterprise_access/apps/subsidy_access_policy/admin.py, enterprise_access/apps/subsidy_access_policy/constants.py
1. Updates `user_message` for the `REASON_LEARNER_NOT_IN_ENTERPRISE` and `REASON_CONTENT_NOT_IN_CATALOG` reason types to have more explicit messaging on the course run card(s) in the Learner Portal UX.
2. Makes the subsidy access policy Django Admin pages a bit easier to work with by adding some additional display fields in the table, filters, and a search bar.
=> fix: update UX messages for non redeemable policies

enterprise_access/settings/utils.py
the x-request-id logging is not working - splunk-connector errors. perhaps there is something magical about `request_id` so lets rename it to `rid` which is less likely to be in use elsewhere. if this does not work i will begin to revert stuff.
=> fix: testing a theory

requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
https://github.com/openedx/edx-rest-api-client/pull/272
=> chore: edx-rest-api-client==5.5.2

enterprise_access/apps/api/v1/views/subsidy_access_policy.py, enterprise_access/apps/subsidy_access_policy/exceptions.py, enterprise_access/apps/subsidy_access_policy/models.py
Take advantage of https://github.com/openedx/enterprise-subsidy/pull/104
...to raise a 422 instead of uncaught 500 when the chained calls to subsidy API -> enterprise enrollment API fail.
=> feat: use more structured redeem error response from subsidy api

enterprise_access/__init__.py, enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py, enterprise_access/apps/subsidy_access_policy/content_metadata_api.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/test_models.py, enterprise_access/apps/subsidy_access_policy/utils.py
https://2u-internal.atlassian.net/browse/ENT-7199
Features:
* Adds a `content_metadata_api` module to encapsulate the fetching and caching of content metadata and catalog inclusion.
* The `SubsidyAccessPolicy` is modified to interact with this module for content needs, rather than going directly to the catalog or subsidy client.
* Introduces optional kwarg to `can_redeem()` to skip the check for learner inclusion in a customer.  We now call `can_redeem` with that kwarg set to True from the view, which is being requested by an already authN'd user, who a priori must be a member of the customer.
* Adds optional settings `CACHE_KEY_VERSION_STAMP` and `CONTENT_METADATA_CACHE_TIMEOUT` to control key-based cache eviction and timeouts for cached content metadata, respectively.
* I've tried to …
=> feat: cache content metadata and containment

enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/urls.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py
* Keeps /api/v1/policy as a duplicated route alongside it for now.
* Removes the /api/v1/policy/redemption view
https://2u-internal.atlassian.net/browse/ENT-7151
There will be nearly-duplicate entries in http://localhost:18270/api/schema/redoc/#tag/Subsidy-Access-Policy-Redemption until the original (now deprecated) `/api/v1/policy` route is removed.
=> refactor: add /api/v1/policy-redemption route

enterprise_access/settings/utils.py
- we want a space after the `[request_id <id>]` and the log info after (eg `middleware.py`)
=> fix: tweak logging whitespace

docker-compose.yml, enterprise_access/settings/devstack.py, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
Before this change: the django cache config is just using local memory cache (surprise!).
After this change: the django cache config points at the memcached container we already have setup for enterprise-access devstack.
You'll have to run `make dev.down dev.up.build` to get the requirements and docker network connection right.
Proof that it works locally:
```
>>> cache.set('foo', 22)
>>> cache.get('foo')
22
>>> settings.CACHES
{'default': {'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache', 'LOCATION': 'enterprise_access.memcache:11211'}}
```
=> feat: memcached config and package for devstack

enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/subsidy_api.py, enterprise_access/apps/subsidy_access_policy/tests/test_models.py
https://2u-internal.atlassian.net/browse/ENT-7221
To find existing redemptions in can_redeem, we now make a single call per _subsidy_ to list transactions for the learner, the result of which we map out in a dictionary variable in the view, by content and policy identifiers, and then store in the request cache.  Caching per request allows us to reuse these results later if we need to determine the amount spent by the learner in a policy is below the policy's learner-level spend cap.
=> fix: refactor can_redeem to make one call per subsidy to fetch all learner txs

enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/subsidy_api.py, enterprise_access/apps/subsidy_access_policy/tests/test_subsidy_api.py, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
https://2u-internal.atlassian.net/browse/ENT-7222
We don't need to request learner aggregates when we make that “bulk” call introduced in ENT-7221 - the policy layer will compute its own aggregates for the learner in memory. This change sets `include_aggregates=False` in subsidy client call to fetch all transactions for a given learner within a subsidy.
=> feat: don't request aggregates when we don't need them

enterprise_access/apps/subsidy_access_policy/subsidy_api.py, enterprise_access/apps/subsidy_access_policy/tests/test_subsidy_api.py
We didn't previously account for multiple active policies all tied to a single subsidy in creating this mapping, even though that situation will be common.  Also adds a unit test to cover the creation of this mapping.
https://2u-internal.atlassian.net/browse/ENT-7230
=> fix: redemption mapping bug fix

requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
Gets the python upgrades from https://github.com/openedx/edx-enterprise-subsidy-client/releases/tag/0.3.7
=> chore: upgrade subsidy client and django utils

enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py
Prior to this change, if the requesting learner has an existing reversed transaction (i.e. they redeemed content, then unenrolled), subsequent calls to can_redeem on the same content would result in a response containing can_redeem=False.  After this change, the response will contain can_redeem=True.  This is achieved by narrowing the scope of what counts as a currently active redemption to also require a non-existent or non-committed reversal.
ENT-7204
=> feat: existing reversed transaction should not prevent redemption

enterprise_access/apps/subsidy_access_policy/utils.py
The default key length in memcached is 250 bytes: https://github.com/memcached/memcached/blob/e0e415b7b2b43a6ddd01a9c3ad45fb46358d526b/memcached.h#L68
Let's sha512() hash every key so we're guaranteed to stay under that limit.  This should result in a 128 byte string in python 
```python
hashlib.sha512('abcdefghijklmnopqrstuvwxyz'.encode()).hexdigest().encode()
len(hashlib.sha512('abcdefghijklmnopqrstuvwxyz'.encode()).hexdigest().encode())
```
=> feat: hash the cache key to stay under max memcached length

enterprise_access/apps/subsidy_access_policy/admin.py
- improve list view
- sort by modified
- include truncated description
=> feat: django admin QoL

enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/test_models.py
https://2u-internal.atlassian.net/browse/ENT-7262
Before this fix, learner-level and policy-level spend limits were not enforced because a sum of negative numbers will always be less than a spend cap defined as a positive integer.
=> fix: account for fact that transaction quantities are almost always negative

enterprise_access/apps/subsidy_access_policy/admin.py
fixes ` TypeError: float() argument must be a string or a number, not 'NoneType'`
=> fix: don't do division on null

enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/events/data.py, enterprise_access/apps/events/tests/test_data.py, enterprise_access/apps/events/tests/test_utils.py, enterprise_access/apps/subsidy_access_policy/mocks.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/factories.py, enterprise_access/apps/subsidy_access_policy/tests/test_models.py
Removes `group_uuid` from the subsidy access policy model, and all related code within this repo. The migrations HAVE NOT bene run yet on this PR and will be done in the following PR.
=> feat: Removes 'group_uuid' field from SubsidyAccessPolicy

enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py
ENT-7319
This avoids an edge case where a learner accesses a learner portal course about page for a course that _cannot_ be redeemed via a new enterprise subsidy.  We shouldn't assume that we can fetch a course list price under that condition, because the content may not be associated with any catalog for the customer.
=> fix: don't fetch list price unless redeemable

enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/api/tests/test_serializers.py, enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/urls.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py
Removes the `/api/v1/policy` endpoint in favor of the `/api/v1/policy-redemption` endpoint using the `SubsidyAccessPolicyRedeemViewset` viewset. Retains `/api/v1/admin/policy` endpoint.
Also removes the `list` endpoint from the `SubsidyAccessPolicyRedeemViewset`
=> feat: Remove `/policy` endpoint

enterprise_access/apps/api/filters/base.py, enterprise_access/apps/api/serializers/__init__.py, enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py
ENT-7149
We want to refactor the policy update API endpoint in a way that makes the permission-ing more obvious and clearly defines the signature of the API using distinct request and response serializers.
This PR changes the SubsidyAccessPolicyViewSet to define `update()` and `parital_update()` actions.
Note, this viewset is already hooked up to a router at the `/api/v1/subsidy-access-policies/` path.
The following fields are allowed to be updated:
- description
- catalog_uuid
- subsidy_uuid
- access_method
- per_learner_enrollment_limit
- per_learner_spend_limit
- spend_limit
Requesting to modify any other field will result in a `ValidationError`.
We use the existing `SubsidyAccessPolicyResponseSerialize`r to output the updated policy record.
Permissions: only the system wide roles that …
=> feat: support update/partial_update in SubsidyAccessPolicyViewSet.

enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py, enterprise_access/apps/subsidy_access_policy/constants.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/test_models.py
Adds more reasons and an additional error message for learner credit in the `SubsidyAccessPolicy` model for the `can_redeem` endpoint. 
Additional logic needed within the enterprise-subsidy repository to specify if a subsidy is not active by checking `isActive` within the subsidy `can_redeem` endpoint
Pending Tests
=> feat: Adds additional error reasons to SubsidyAccessPolicy

enterprise_access/apps/api/v1/views/subsidy_access_policy.py, enterprise_access/apps/subsidy_access_policy/models.py
I frequently want this for faster investigation.
=> feat: log can_redeem results in viewset's evaluate_policies

enterprise_access/apps/subsidy_access_policy/models.py
Reorders the messaging from can_redeem to match figmas expected order of operation for error messaging return
=> feat: change which reasons are selected for a non-redeemable policy

enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/test_models.py
We should wait to fetch data from enterprise-subsidy until we know we actually need it.
=> fix: when we fetch inter-service data in can_redeem matters for perf

enterprise_access/apps/subsidy_access_policy/content_metadata_api.py, enterprise_access/apps/subsidy_access_policy/subsidy_api.py
I noticed recently that we do a lot of logging of cache keys that are opaque.  This change removes those logs and replaces them with a logging statement only when we fetch data from another service.
=> fix: don't log useless/opaque cache keys.

docs/decisions/0011-subsidy-access-policy-crud-api-definition.rst, docs/decisions/README.rst
The purpose of this ADR is to summarize the mapping of client use cases to policy REST endpoints. It does *not* exhaustively define inputs, outputs, error codes, etc. - those are captured in the live API docs pages, to which this document refers.
=> docs: ADR on policy CRUD API contract.

Makefile, docker-compose.yml, enterprise_access/settings/devstack.py
- https://2u-internal.atlassian.net/browse/ENT-7470
- standing on the shoulders of giants https://github.com/openedx/enterprise-subsidy/pull/141
```
make dev.up
make dev.dbcopy8
make app-restart
```
Then login to the admin site to ensure your data was copied: http://localhost:18270/admin/ 
Note that the new mysql 8 container is running side-by-side with mysql 5.7 for now.  For mysql 8, the container's 3306 port is bound to the host's 3406 port, so use 3406 if you use a mysql IDE or something locally.
=> build: switch to mysql 8

enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/urls.py
Deprecates the `admin/policy` endpoint using the `SubsidyAccessPolicyCRUDViewset` in favor of `subsidy-access-policies` endpoint using the `SubsidyAccessPolicyViewSet`.
Refactor tests and verified its still working in the frontend with this refactor PR -> https://github.com/openedx/frontend-app-support-tools/pull/347
=> feat: Deprecate old 'admin/policy' endpoint

enterprise_access/apps/api/v1/views/subsidy_access_policy.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/test_models.py
- https://2u-internal.atlassian.net/browse/ENT-7484
- when multiple redeemable policies are present, resolve them first by type, then expiration date, then balance
- utilize `RequestCache` to avoid multiple round-trips to subsidy service
- gate this experimental functionality behind a setting, allowing us to observe performance in a controlled fashion on STAGE
=> feat: multi-policy resolution

enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/api/tests/test_serializers.py, enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py
**Change**: Add a new field "subsidy_end_date" in Credits Available response serializer. 
**Reason**: We need this data on frontend to show when the policy is going to expire. It will be displayed against the "Available Until" header.
=> feat: add expiration date field in credits serializer

.annotation_safe_list.yml, enterprise_access/apps/content_assignments/models.py
=> docs: add missing model annotations for PII

enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py
https://2u-internal.atlassian.net/browse/ENT-7595
Builds on top of https://github.com/openedx/enterprise-access/pull/246
=> feat: expose display_name via REST API. ENT-7595

enterprise_access/apps/subsidy_access_policy/subsidy_api.py, enterprise_access/apps/subsidy_access_policy/tests/test_subsidy_api.py
When there is more than 1 page of learner transactions to traverse, we hit a bug like the following:
```
‘Response’ object is not subscriptable
at /edx/app/enterprise-access/enterprise_access/apps/subsidy_access_policy/subsidy_api.py, line 58, in get_and_cache_transactions_for_learner
```
This is because we’re trying to access data from the response object, instead of getting the payload out of the response.json() result.
This PR uses `response.json()` so that we actually access the payload during pagination.
https://2u-internal.atlassian.net/browse/ENT-7637
=> fix: paginate pages of user transactions correctly. ENT-7637

enterprise_access/apps/subsidy_access_policy/models.py
This change handles the scenario when `spent_amount` comes to be `None`.
=> fix: unsupported operand type for remaining balance

enterprise_access/apps/api/serializers/assignment_configuration.py, enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/api/v1/tests/test_assignment_configuration_views.py, enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/views/assignment_configuration.py, enterprise_access/apps/content_assignments/models.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/factories.py, enterprise_access/apps/subsidy_access_policy/tests/test_models.py, enterprise_access/utils.py
In adding another type of SubsidyAccessPolicy, I was finding it harder to write validation logic around what types of fields
certain policy types *must* have and which they *must not* have, in a way that was consistent across the model level and the DRF serialization level.
Background:
1. It's really nice to have some validation of fields on model instances at the point where the instance has been created/updated in-memory, but not yet saved.  This helps validate model instance manipulation across Django Admin and our business logic layers.
2. DRF _really_ doesn't want to do model-level validation in serializers; it strongly prefers to validate inputs *before* doing any in-memory model instance manipulation.  See https://www.django-rest-framework.org/community/3.0-announcement/#differences …
=> feat: policy validation refactor, policy -> assignment dependency strictness

conftest.py, enterprise_access/apps/api_client/lms_client.py, enterprise_access/apps/api_client/tests/test_lms_client.py, enterprise_access/apps/content_assignments/tasks.py, enterprise_access/apps/content_assignments/tests/test_tasks.py
=> feat: add task to create a pending enterprise learner for an assignment

enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/content_assignments/constants.py, enterprise_access/apps/content_assignments/models.py, enterprise_access/apps/content_assignments/tests/test_api.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/settings/devstack.py
=> feat: add allocate_assignments method to content_assignments app.

enterprise_access/apps/api/serializers/__init__.py, enterprise_access/apps/api/serializers/content_assignments.py, enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/api/v1/tests/test_allocation_view.py, enterprise_access/apps/api/v1/urls.py, enterprise_access/apps/api/v1/views/__init__.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py, enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/content_assignments/tests/test_api.py, enterprise_access/apps/core/constants.py, enterprise_access/apps/core/rules.py, enterprise_access/apps/subsidy_access_policy/models.py
* Adds authorization rules that only assingment operators/admins, or policy operators, can allocate (basically enterprise admins or openedx operators).
* Adds `/api/v1/policy-allocation/[policy_uuid]/allocate` route to API.
* Serializes the result from the assignments API `allocate_assignments()` function.
* Basic error handling and lock-error handling.
* Takes the position that no positive integer quantity amounts can be allocated.
http://localhost:18270/api/schema/redoc/#tag/Subsidy-Access-Policy-Allocation
If you want to test in postman or curl:
```
curl --location 'http://localhost:18270/api/v1/policy-allocation/[YOUR_POLICY_UUID]/allocate/' \
--header 'Authorization: JWT [YOUR_JWT_HERE]' \
--header 'Content-Type: application/json' \
--data-raw '{
"learner_emails": …
```
=> feat: policy allocation endpoint

enterprise_access/apps/api/v1/tests/test_assignment_views.py, enterprise_access/apps/api/v1/views/content_assignments/assignments.py
My last PR was missing some unit tests (added in this commit) which led to me missing the fact that learner-facing assignments endpoints were broken due to misconfigured ViewSet permissions.
ENT-7680
=> fix: learner-facing assignments endpoints broken

enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/api/v1/tests/test_allocation_view.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py, enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/content_assignments/models.py, enterprise_access/apps/content_assignments/tests/test_api.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/test_models.py
https://2u-internal.atlassian.net/browse/ENT-7689
Couple of main things here.
* Everything above the model/persistence layer now expects to deal in **non-negative** content prices in cents.  That is, the allocate view layer, serialization/validation, and business logic layers all want positive prices in cents, which are converted to negative `content_quantities` before assignment model instances are created/updated.
* We previously didn't have a good happy path, end-to-end test case for requests to the allocate view all the way through the `can_allocate()` business logic checks in the policy layer.  We now have such test cases.
* Changes in the allocate view to return more structured 422 responses, with reason-for-non-allocation error codes and corresponding user-facing messages; very …
=> feat: allocate view expects non-negative content price. provide well-serialized non-allocation reasons

enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/api/tests/test_serializers.py, enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/subsidy_access_policy/constants.py, enterprise_access/apps/subsidy_access_policy/models.py
* Adds an "aggregates" key to the policy serializer containing a nested dict of values.
- `amount_redeemed_usd_cents`: Total amount currently redeemed (positive USD Cents).
- `amount_redeemed_usd`: Same as above, in USD dollars.
- `amount_allocated_usd_cents`: Total amount currently allocated (positive USD Cents).
- `amount_allocated_usd`: Same as above, in USD dollars.
- `spend_available_usd_cents`: Total amount currently available to spend (positive USD Cents).
- `spend_available_usd`: Same as above, in USD dollars.
* Removes unnecessarily layer of abstraction: remaining_balance() method deleted.
* Adds a missing policy type enum value: PolicyTypes.ASSIGNED_LEARNER_CREDIT
ENT-7693
=> feat: serialize aggregates for policies to support budget details

enterprise_access/apps/api/serializers/content_assignments/assignment_configuration.py, enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/api/v1/tests/test_assignment_configuration_views.py, enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/subsidy_access_policy/admin.py
also, fixes policy django admin pages to not display policy serialization when adding a new record.
=> fix: nested serialization of assignment config within policy

enterprise_access/settings/base.py
**Description**:
The setting JWT_AUTH_REFRESH_COOKIE is meaningless and unused and should be cleaned up to avoid confusion.
In the very early days of introducing MFEs, we thought we were going to need this cookie in addition to the JWT cookie. However, it turned out we didn't need it, but the setting stuck around the contagion of it (being in cookiecutter and other template libraries) has resulted in it uselessly being copied to many repos.
**Supporting information:**
as per the original ticket https://github.com/openedx/public-engineering/issues/190, this setting is removed.
**Rationale**
The setting JWT_AUTH_REFRESH_COOKIE is meaningless and unused, and should be cleaned up to avoid confusion.
In the very early days of introducing MFEs, we thought we were going to need this cookie in …
=> feat: remove JWT_AUTH_REFRESH_COOKIE depr190

enterprise_access/apps/api/serializers/__init__.py, enterprise_access/apps/api/serializers/content_assignments/assignment.py, enterprise_access/apps/api/v1/tests/test_allocation_view.py, enterprise_access/apps/api/v1/tests/test_assignment_views.py, enterprise_access/apps/api/v1/views/content_assignments/assignments.py, enterprise_access/apps/api/v1/views/content_assignments/assignments_admin.py, enterprise_access/apps/content_assignments/constants.py, enterprise_access/apps/content_assignments/models.py
Assignment serializer contains three additional output keys:
* `actions` (list of dict): A list of all serialized actions for the assignment.
* `recent_action` (dict): intended to power the "Recent action" column in the frontend display.
* `learner_state` (str): intended to power the "Status" column in the frontend display.
Assignment list views are now sortable on two keys:
* `learner_state_sort_order`: This sorts based on the internal sort order of dynamic field `learner_state`.
* `recent_action_time`: This is a dynamic field defined as `coalesce(most recent reminder, assignment creation)`
Sample URLs
-----------
Listing assignments sorted by learner_state:
```
/api/v1/assignment-configurations/{assignment_configuration_uuid}/admin/assignments/?ordering=learner_state_sort_order …
```
=> feat: [assignments] backend support for "State" and "Recent action" columns

enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/subsidy_access_policy/models.py
This protection against crashing is nice because we use the serializer in django admin, so bad data also crashes django admin.
=> fix: serializer no longer crashes on bad data

enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/subsidy_access_policy/content_metadata_api.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/subsidy_api.py, enterprise_access/apps/subsidy_access_policy/utils.py, enterprise_access/cache_utils.py
This will eventually support the creation of a `content_metadata` module, and we'll yank stuff out of the `subsidy_access_policy` module into this new module.  We need a `content_metadata` module that both the `subsidy_access_policy` and `content_assignments` app depend on; we don't want the latter depending on the former.
=> refactor: create cache_utils.py, move stuff there

enterprise_access/apps/content_assignments/apps.py, enterprise_access/apps/content_assignments/signals.py, enterprise_access/apps/content_assignments/tests/test_signals.py
During the post_save hook for core.User, lookup any existing assignments for the user and populate the lms_user_id into the assignments.  This should happen whenever the user logs in, so it theoretically covers the case where a learner is assigned content before authing with enterprise-access.
The case where a learner is assigned content AFTER authing with enterprise-access would be covered by ENT-7874.
ENT-7875
=> feat: populate assignment.lms_user_id on core.User.save()

enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/api/v1/tests/test_allocation_view.py
Stops requiring allocate request payload `content_key` to be a valid opaque key.
=> fix: allow non-opaque-keys as content key for allocate requests

enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/settings/local.py
We often want to understand which SQL statements are executed by the Django ORM, here's a change in `settings/local.py` to optional enable this via a setting in `private.py`.
=> chore: allow optional logging of Django's SQL

enterprise_access/apps/api/v1/tests/test_allocation_view.py, enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/content_assignments/tests/test_api.py
- @adamstankiewicz was integration testing and noticed missing content titles on new assignments
- i realized i had [the wrong summary key](https://github.com/openedx/enterprise-subsidy/blob/main/enterprise_subsidy/apps/content_metadata/api.py#L110)
=> fix: missing content titles on assignments

enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/content_assignments/tests/factories.py, enterprise_access/apps/content_assignments/tests/test_api.py, enterprise_access/apps/content_assignments/utils.py
This is an attempt to cover the case where learners are already logged in at the moment of assignment.  This case is a hole left by the work in ENT-7875 which only set out to cover the case where a learner was logged out at the moment of assignment.
ENT-7874
=> feat: Try to populate lms_user_id on assignments during creation

enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py
**Description**: This PR adds the learner content assignments to the [credits_available endpoint](http://localhost:18270/api/v1/policy-redemption/credits_available/?enterprise_customer_uuid=d1303765-90f9-4e01-9eaa-654c943fbd60&lms_user_id=3)
**JIRA** : ENT-7870
**Sample Output**
=> feat: Added assignments in credits_available endpoint

enterprise_access/apps/api/serializers/content_assignments/assignment.py, enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py, enterprise_access/apps/api_client/enterprise_catalog_client.py, enterprise_access/apps/api_client/tests/test_enterprise_catalog_client.py, enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/content_metadata/api.py, enterprise_access/apps/content_metadata/tests/test_api.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/settings/devstack.py
This change allows us to pull-through content metadata from the enteprise-catalog `get_content_metadata` endpoint into serialized assignments contained within responses of the `credits_available` view.  
For example, in response to
```
curl --location 'http://localhost:18270/api/v1/policy-redemption/credits_available/?enterprise_customer_uuid=70699d54-7504-4429-8295-e1c0ec68dbc7&lms_user_id=8' \
```
you'd get 
```
[
{
"uuid": "3cc0ad2c-ede1-476c-8271-97683855e41d",
"policy_redemption_url": "http://localhost:18270/api/v1/policy-redemption/3cc0ad2c-ede1-476c-8271-97683855e41d/redeem/",
"remaining_balance_per_user": null,
"remaining_balance": 482847,
"subsidy_expiration_date": "2024-03-15T18:48:26Z",
"learner_content_assignments": [
{
"uuid": "a7e12cd7-4c9a-41ef-82a6-bea4c9be0521", …
```
=> Fetch content metadata for serialized assignments in `credits_available` response payload

enterprise_access/apps/api/serializers/content_assignments/assignment.py, enterprise_access/apps/api/v1/tests/test_assignment_views.py, enterprise_access/apps/api/v1/views/content_assignments/assignments_admin.py, enterprise_access/apps/api/v1/views/utils.py
In order to support the default behavior of `DataTable` filtering with checkboxes on the "Status" column of the "Assigned" table in the Learner Credit Management's budget detail page, the paginated response of the admin content assignments list API now returns a `learner_state_counts` field that will adhere to any queryset filters, etc.
Allows the frontend UI to iterate over `learner_state_counts` to display the following:
```python
{
"next": null,
"previous": null,
"count": 21,
"num_pages": 1,
"current_page": 1,
"start": 0,
"results": [
{
"uuid": "b8cf11f9-8589-42d0-83d7-0e938636a8d8",
"assignment_configuration": "d17b7d66-8289-404e-90a5-d534ead459f6",
"learner_email": "[edx+018@example.com](mailto:edx+018@example.com)",
"lms_user_id": null,
"content_key": "ColumbiaX+CSMM.104x", …
```
=> feat: return `learner_state_counts` as part of the admin assignments list API response

enterprise_access/apps/api/v1/tests/test_allocation_view.py, enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/content_assignments/tasks.py, enterprise_access/apps/content_assignments/tests/test_api.py
Modifies `allocate_assignments()` to call an async task to link the assignment's user to the relevant enterprise, for all updated or created assignments.
https://2u-internal.atlassian.net/browse/ENT-7778
=> feat: link learners during assignment allocation

enterprise_access/apps/api/filters/base.py, enterprise_access/apps/api/filters/content_assignments.py, enterprise_access/apps/api/v1/tests/test_assignment_views.py, enterprise_access/apps/api/v1/views/content_assignments/assignments_admin.py
* Ensures `content_quantity` can be used with `?ordering`.
* Ensures `learner_state` ("Status" column) can be filtered by one or more values at a time (e.g., `learner_state=waiting`, `learner_state=notifying,failed`).
* Refactors how `learner_state_counts` is generated to no longer rely on `.values('learner_state').annotation(count=Count('uuid', distinct=True))`, which seems to be causing the exception seen in the following screenshot locally (not in stage/prod, though?). API now relies on `Counter` to determine the counts of each `learner_state`. It also now ensures `self.filter_queryset()` is called before generating these counts.
=> fix: new approach to generate `learner_state_count` in admin assignments list API; add addtl ordering and filtering support

docs/decisions/0014-assignment-price-validation.rst, docs/decisions/README.rst
This ADR describes an approach to validating client-provided allocation prices.  The implementation way previously merged in https://github.com/openedx/enterprise-access/pull/323/files
https://2u-internal.atlassian.net/browse/ENT-7953
=> docs: ADR on client-provided allocation price validation

enterprise_access/apps/api/v1/views/subsidy_access_policy.py, enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/content_assignments/tasks.py
...in which we re-learn the lesson of invoking async celery tasks _outside_ of `transaction.atomic()` blocks.
The race condition occurs like so:
```
[MAIN PROC] DB TRANSACTION STARTS
[MAIN PROC] ASSIGNMENT ALPHA CREATED
[MAIN PROC] ASYNC TASK TO LINK LEARNERS INVOKED
[MAIN PROC] ...OTHER ASSIGNMENTS CREATED.
[CELERY WORKER PROC] TASK STARTS, GIVEN ALPHA UUID ARG
[CELERY WORKER PROC] TASK READS ASSIGNMENT TABLE FOR ALPHA UUID
[CELERY WORKER PROC] NO ASSIGNMENT WITH ALPHA UUID EXISTS, RAISE
[MAIN PROC] TRANSACTION COMMITTED
```
=> fix: avoid race condition during assignment allocation

enterprise_access/apps/content_assignments/models.py, enterprise_access/apps/content_assignments/tasks.py, enterprise_access/apps/content_assignments/tests/test_tasks.py, enterprise_access/apps/content_assignments/utils.py
ENT-7981 | Records an errored learner-linking action when the call to link pending learners fails during assignment allocation.
Locally, I forced my lms client method to raise an HTTPError on the pending learners call.
=> fix: record error action when learner-linking task fails.

enterprise_access/apps/api/v1/tests/test_allocation_view.py, enterprise_access/apps/content_assignments/api.py
1. `full_clean()` actually runs queries to validate uniqueness, and we don't need that here. switch to `clean()` instead. https://docs.djangoproject.com/en/4.2/ref/models/instances/#django.db.models.Model.full_clean
2. We only need to fetch the content title once, outside of the loop to create assignments.
3. Prefetch updated/created assignments at the tail end of allocation, so that any downstream serializers don't need to do N queries for actions.
=> perf: improve allocate view latency

enterprise_access/apps/api/filters/content_assignments.py, enterprise_access/apps/api/v1/tests/test_assignment_views.py
ENT-7809 | Allow all fields that we filter assignments by to accept either exact filtering or "in" filtering.  This slightly changes the current usage of filtering on "learner_state" to remain consistent. Callers must now request filters on this field as "learner_state__in=state1,state2" instead of "learner_state=state1,state2".
=> feat!: allow in expr filtering for assignment view fields

enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/subsidy_access_policy/admin.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/test_models.py
ENT-7988 | Create an assigned policy's `assignment_configuration` on save() if none is present. Clean up django admin form for assigned policies.
=> feat: create assigned policy configuration on save

enterprise_access/apps/content_assignments/tasks.py
- https://2u-internal.atlassian.net/browse/ENT-8031
- new relic alert paged me
- everywhere else in the code `normalized_metadata` is accessed its via `.get()` as if its not always there
- applying same pattern here
```
ubuntu@ip-172-31-34-253:~/edx-repos/enterprise-access$ grep -r normalized_metadata
grep: .git/objects/pack/pack-a6d5c57132f9f5afaa6c97138e5aea61488639e9.pack: binary file matches
enterprise_access/apps/content_assignments/tasks.py:        braze_trigger_properties["enrollment_deadline"] = course_metadata['normalized_metadata']['enroll_by_date']
enterprise_access/apps/content_assignments/tasks.py:        braze_trigger_properties["start_date"] = course_metadata['normalized_metadata']['start_date']
enterprise_access/apps/content_assignments/tasks.py: …
```
=> fix: safely access dictionary

enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/test_models.py
Ensures that when an assignable budget/policy’s enterprise customer UUID is updated, the associated AssignmentConfiguration's enterprise customer UUID is also updated (these should always match).
ENT-8036
https://github.com/openedx/enterprise-access/assets/2307986/5f22afd8-cfc4-4aac-83bc-79090bba0113
=> fix: prevent drift in existing assignment config customer uuids

enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/content_assignments/tests/test_api.py
ENT-8037 | De-duplicate learner emails prior to executing allocation logic.
=> fix: de-duplicate emails on the way into allocation logic

enterprise_access/apps/api/v1/tests/test_assignment_views.py, enterprise_access/apps/api_client/braze_client.py, enterprise_access/apps/content_assignments/content_metadata_api.py, enterprise_access/apps/content_assignments/models.py, enterprise_access/apps/content_assignments/tasks.py, enterprise_access/apps/content_assignments/tests/test_api.py, enterprise_access/apps/content_assignments/tests/test_content_metadata_api.py, enterprise_access/apps/content_assignments/tests/test_tasks.py
* Send aliased recipient when no lms_user_id on assignment (Braze API won't accept request otherwise).
* Task retries should result in only 1 errored action.
* Even safer date parsing (account for possible microseconds).
* Fetch course metadata record inside assignment tasks properly.
ENT-8066
=> fix: braze alias stuff and other fixes

enterprise_access/apps/content_assignments/tasks.py, enterprise_access/apps/content_assignments/utils.py, enterprise_access/settings/devstack.py
Pluck the response content from the underlying HTTPError when handling `BrazeBadRequestError`.
=> fix: slightly better braze exception handling

test_utils/__init__.py
I noticed that the base API test case was re-creating a user to use for the test client for every single test of an API view.  And the same user. With the same username/email/password.  This seemed costly on my machine, so I moved it to setUpClass().
=> perf: faster base API Test case

enterprise_access/apps/content_assignments/tasks.py
Some logging to help us understand
1. What trigger properties we're sending for assignment braze campaigns.
2. when we're sending an empty `course_card_image` property, if ever.
=> fix: more logging for assignment email tasks

enterprise_access/apps/api/filters/subsidy_access_policy.py, enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py
Adds optional filtering by `active` policies to the the subsidy-access-policy filter file.
=> feat: adds optional filtering by active subsidy access policies

enterprise_access/apps/api_client/braze_client.py, enterprise_access/apps/content_assignments/tasks.py, enterprise_access/apps/content_assignments/tests/test_tasks.py
We have to create an alias record in Braze before sending campaign messages to emails that aren't currently identified in braze.  e.g.
this works now.
=> fix: create braze alias when sending assignment emails

enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/test_models.py
Store policy aggregates in the request cache, so that the policy list view isn't ridiculously slow.  It used to make lots of calls to subsidy for a single list call - 4 calls to the subsidy service per single policy, all to compute the aggregates, which won't change in the scope of our list request.
Before (4 calls per policy)
```
enterprise_access.app  | 2023-12-07 14:36:11,673 DEBUG 972 [urllib3.connectionpool] [user 1] [ip 172.20.0.1] [request_id None] connectionpool.py:547 - http://enterprise-subsidy.app:18280 "GET /api/v2/subsidies/4c53f616-5ea0-42a0-9430-ba165cb2c916/admin/transactions/?state=committed&state=pending&state=created&include_aggregates=True&subsidy_access_policy_uuid=3cc0ad2c-ede1-476c-8271-97683855e41d HTTP/1.1" 200 962
enterprise_access.app  | 2023-12-07 14:36:11,749 …
```
=> perf: cache policy aggregates

enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py, enterprise_access/apps/subsidy_access_policy/constants.py
ENT-8114 | The can-redeem endpoint now returns a reason and user message related to policies that are unredeemable due to a lack of allocated `LearnerContentAssignment` record for the requesting user, or the existence of an assignment in a `CANCELLED` or `ERRORED` state.
Sample response payload for my local policy that does *not* have an assignment for the requesting test user:
```
[
{
"content_key": "course-v1:edX+DemoX+Demo_Course",
"list_price": null,
"redemptions": [],
"has_successful_redemption": false,
"redeemable_subsidy_access_policy": null,
"can_redeem": false,
"reasons": [
{
"reason": "reason_learner_not_assigned_content",
"user_message": "You can't enroll right now because this course is not assigned to you.",
"policy_uuids": [
"3cc0ad2c-ede1-476c-8271-97683855e41d"
], …
```
=> feat: can-redeem user message for no/cancelled/errored assignments

enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/content_assignments/signals.py, enterprise_access/apps/content_assignments/tests/test_api.py, enterprise_access/apps/content_assignments/tests/test_signals.py
ENT-8129 | The email stored on assignment records might be only a case-insensitive match to the corresponding email in the core.User records, so do case-insensitive matching during the assignment flow and during the post-user-save signal that updates assignment ``lms_user_ids``.
=> fix: compare emails case-insensitively when setting assignment lms_user_ids

enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/content_assignments/tests/test_api.py
ENT-8129 | Also do filters for existing assignments against a batch of emails to allocate in a case-insensitive manner.  Helps in the case where a client allocates to `foo@bar.com` at time t1 and against attempts to allocate to `FOO@bar.com` at time t2.  No second assignment record will be written for `FOO@bar.com`.
=> fix: case-insensitive email matching for existing assignments

enterprise_access/apps/api_client/braze_client.py
Fix for https://2u-internal.atlassian.net/browse/ENT-8144
=> fix: ENT-8144 When adding learners to braze ensure they are tagged as enterprise learners

enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/content_assignments/tests/test_api.py, enterprise_access/apps/subsidy_access_policy/tests/test_models.py
Content Assignments need to be able to figure out the canonical `course_key` from a `course_run_key`. Previously this was done via the syntax/structure of the key itself. This fails in situations where the `course_run_key` is not properly formed. Example provided in the ticket.
This new implementation leverages the content summary data provided by enterprise-subsidy service. The content summary utilizes the enterprise-catalog data which stores the course-key/run-key relationships as it unpacks the content metadata from discovery - regardless of how keys are structured within that document. In other words, it doesn't need to evaluate the key syntax/structure so it is tolerate of non-conforming keys.
- https://2u-internal.atlassian.net/browse/ENT-8125
=> fix: content summary course key normalization

enterprise_access/apps/api/filters/content_assignments.py, enterprise_access/apps/api/v1/tests/test_assignment_views.py, enterprise_access/apps/api/v1/views/content_assignments/assignments_admin.py
ENT-8156 | The remind-all and cancel-all views for content assignments
are now filterable by anything the list view can be filtered by,
included the `learner_state` attribute.
=> feat: allow cancel/remind-all assignments views to be filterable

enterprise_access/apps/content_assignments/management/commands/automatically_expire_assignments.py, enterprise_access/apps/content_assignments/management/commands/tests/test_automatically_expire_assignments.py
The `automatically_expire_assignments` command is now more defensive about fetching content metadata for assignment records.
https://2u-internal.atlassian.net/browse/ENT-8205
=> fix: be defensive in content metadata fetching for assignment expiration

enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/content_assignments/content_metadata_api.py, enterprise_access/apps/content_assignments/management/commands/automatically_expire_assignments.py, enterprise_access/apps/content_assignments/management/commands/tests/test_automatically_expire_assignments.py
Part of ENT-7557, refactors expiration business logic into the `content_assignments.api` module, so its
clearer where to find the logic that determines whether and when an assignment is expired.
=> refactor: assignment expiration

docs/decisions/0016_automatic_expiration.rst, enterprise_access/apps/api/v1/tests/test_assignment_views.py, enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/content_assignments/constants.py, enterprise_access/apps/content_assignments/management/commands/automatically_expire_assignments.py, enterprise_access/apps/content_assignments/models.py, enterprise_access/apps/content_assignments/tests/test_api.py, enterprise_access/apps/content_assignments/tests/test_models.py
ENT-7557 | Removes PII on assignment records (and related history) when the record has been in an expirable state for long enough.
There's currently a management command (run via a cron) named ``automatically_exire_assignments.py``
that toggles the state of ``LearnerContentAssignment`` records ("Assignments")
to ``CANCELLED`` under any of the following conditions:
1. The current state of the assignment is ``ALLOCATED``.
2. The current date is more than 90 days after the most recent notification action - this action
time is used as a proxy for understanding *when* the assignment *was last allocated*. This helps
deal with the edge case where an assignment is allocated, cancelled, and re-allocated later.
3. The current date is greater than the inferred enrollment deadline for the assigned …
=> feat: scrub assignment pii on auto-expiration

enterprise_access/apps/content_assignments/models.py, enterprise_access/apps/content_assignments/tests/test_models.py
ENT-8146 | Use the assignment.created time as the starting point for assignment auto-expiration if a successful notification action does not yet exist.
=> fix: assignment auto-expiration date

enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/subsidy_access_policy/exceptions.py
Before this change, the SubsidyAPIHTTPError source code assumed that we can test the truthiness of requests.models.Response as a proxy for existence.  This is a fatal assumption because the Response objects overrides __bool__() in a way that all error codes are falsey. This resulted in completely dropping the error information from the response object.
After this change, error codes will actually be propagated up into error logging tools (New Relic, Splunk, etc.).
requests.models.Response implementation: https://docs.python-requests.org/en/latest/_modules/requests/models/#Response
=> fix: SubsidyAPIHTTPError should not drop the HTTP response error

enterprise_access/apps/content_assignments/management/commands/automatically_nudge_assignments.py
Failing cron job does not recognize the type of argument passed. Defining a type of the value for the argument
=> fix: adds type to cron job argument

enterprise_access/apps/api/v1/views/subsidy_access_policy.py, enterprise_access/apps/content_assignments/api.py
[new PR b/c of weird failing test in github but not local]
* Strips out some logging that was manually timing the allocate endpoint (the endpoint is now performant enough, and we have better tools for this anyway)
* Adds logging around the main function that allocates assignments.
=> feat: remove some timing logs, add allocation logs

Makefile, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
While creating the Ansible playbooks and roles for deploying enterprise-access - https://github.com/openedx/configuration/pull/7107, a couple of issues were discovered with the `production-requirements` make command and the requirements.
This PR includes the following changes:
1. Make the `production-requriements` command depend on the `piptools` command so that it can be run without explicitly running the `piptools` beforehand.
2. Add `pygments` as an explicit requirement.
=> build: fixes for native deployment

enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py
Update the `enterprise_administrators` contact information to the enterprise customer's `contact_email` since we want to prioritize this over the list of `admin_users`. Fall back on the list of `admin_users` if a `contact_email` is not set.
https://2u-internal.atlassian.net/browse/ENT-8418
=> feat: update contact email logic in can_redeem

enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py
Adding group association data to the subsidy policy serializers 
https://2u-internal.atlassian.net/browse/ENT-8617
=> feat: adding group associations to subsidy access policy api serializers

enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/subsidy_access_policy/admin.py
also, broadly try/except the django admin API repr of serialized subsidy access policy records.
=> fix: serialized data should not include querysets

enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/api/tests/test_serializers.py, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/production.txt, requirements/quality.txt, requirements/test.in, requirements/test.txt, requirements/validation.txt
I noticed during stage testing that this field was missing from serialized policies, specifically in the credits_available response.
ENT-8518
=> fix: add missing serializer field `is_late_redemption_allowed`

enterprise_access/apps/subsidy_access_policy/constants.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/test_forced_redemption.py
Keyword required by the subsidy service: https://github.com/openedx/enterprise-subsidy/pull/219 `allow_late_enrollment`
This is the thing that will allow us to not only force redemption, but to force it for courses that are otherwise _closed_ to new enrollments.
=> feat: pass the special keyword during forced redemption

enterprise_access/apps/content_assignments/admin.py, enterprise_access/apps/subsidy_access_policy/admin/__init__.py
In Django Admin, you can't search directly on a Foreign Key model - you have to specify which _field_ of the related model is searchable, even if it's the PK.
=> fix: django admin search on FK field

enterprise_access/apps/api/v1/views/content_assignments/assignments_admin.py, enterprise_access/apps/content_assignments/tasks.py
This is a stop-the-bleeding approach to solving the problem where reminder failures cause the assignment to become inadvertently non-redeemable. This commit results in the remind and remind-all endpoints no longer progressing the assignment lifecycle state to `errored` when the reminder fails for any reason.
Before this PR, clicking remind would cause admins to see the following table cells change:
* Reminder failure:
- Status column: "Waiting for learner" -> "Failed: Reminder"
- Recent action column: "Assigned: \<date\>" -> NO CHANGE
* Reminder success:
- Status column: "Waiting for learner" -> NO CHANGE
- Recent action column: "Assigned: \<date\>" -> "Reminded: \<date\>"
but now they will see:
* Reminder failure:
- Status column: "Waiting for learner" -> NO CHANGE
- Recent action …
=> feat: reminder failures no longer fail assignments

enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/content_assignments/constants.py, enterprise_access/apps/content_assignments/models.py, enterprise_access/apps/content_assignments/tests/test_api.py, enterprise_access/apps/content_assignments/tests/test_models.py
Prior to this change, the `LearnerContentAssignment.clear_pii()` method set a retired email address to the same static value.  This means that if two different learners (by email) in the same assignment configuration (i.e. budget) have the same course assigned, and then those records are expired, the second record to be expired will fail on the unique constraint violation of the model.
This change adds a random hex-string to each retired email address value to help resolve this issue. ENT-8574
=> fix: uniquify retired email addresses

docs/decisions/0019-forced-redemption.rst, docs/decisions/README.rst
There is frequently a need to force through a redemption (and related enrollment/fulfillment)of a particular learner, covered by a particular subsidy access policy, into some specific course run. This ADR proposes a model and methodology for achieving such a redemption.
=> docs: proposed ADR for forced redemption

docs/decisions/0020-redemption-attempt-record.rst
Proposes the introduction of a new Django model, called ``RedemptionAttempt`` (or similar), to persist
business logic outcomes and workflow results in the course of the redemption workflow.
=> docs: proposed ADR for a RedemptionAttempt model

enterprise_access/apps/content_assignments/management/commands/automatically_nudge_assignments.py, enterprise_access/apps/content_assignments/management/commands/tests/test_automatically_nudge_assignments.py
This should fix these errors surfaced by the cronjob:
```
File "/edx/app/enterprise-access/enterprise_access/apps/content_assignments/content_metadata_api.py", line 121, in is_date_n_days_from_now
AttributeError: 'NoneType' object has no attribute 'date'
```
ENT-8789
=> fix: courserun metadata start date key is actually just "start"

enterprise_access/apps/content_assignments/management/commands/automatically_nudge_assignments.py, enterprise_access/apps/content_assignments/management/commands/tests/test_automatically_nudge_assignments.py
This is a fix for a regression I recently introduced. It's actually a supported code path for this particular dict key to point to a Null value if no content metadata was found.
ENT-8789
=> fix: missing content metadata no longer crashes nudge email script

enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/mixins.py, enterprise_access/apps/subsidy_access_policy/tests/test_models.py
Updates usage of `get_enterprise_user` in `includes_learner` for groups, to include an additional argument `enterprise_user_record` which defaults to `None` if nothing is passed. This allows us to pass the learner record in if it exists. If no `enterprise_user_record` exists, it will attempt to retrieve it from the cache, or fetch and initialize the cache via the `get_and_cache_enterprise_learner_record` function.
Modifies `includes_user` to `enterprise_user_record` to return to user record as oppose to resolve its boolean value whether the enterprise_user_record exists. This was modified to reduce the amount of calls to `get_enterprise_user` and the cache by allowing the check of its existence to happen in line, and using the `enterprise_user_record` object if it does …
=> feat: Updates groups learner record check to cached learner record

enterprise_access/apps/api_client/lms_client.py
Platform treats `show_removed` as true if it's included, no matter the value. Therefore, the only way to pass a False value is to omit it entirely.
=> fix: omitting groups with aggregates false query param passed along to platform

enterprise_access/apps/api/v1/views/subsidy_access_policy.py
mishap with num pages pagination response value when sorting by enrollment count
=> fix: updating group members with aggregate pagination num pages

api-compact.yaml, api.yaml
Published the endpoint that allows a user to retrieve the list of Subsidy Access Policies associated with the specified UUID. 
https://enterprise-access-internal.edx.org/api/schema/redoc/#tag/Subsidy-Access-Policies-CRUD/operation/api_v1_subsidy_access_policies_list
**Jira:**
ENT-8718
=> feat: exposed subsidy access policy list endpoint

Makefile, README.rst, enterprise_access/apps/core/management/commands/consume_enterprise_ping_events.py, enterprise_access/settings/devstack.py, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
Installs openedx-events, kafka, and so forth for local development of kafka events.  Upgrades deps due to installation of events packages. Provides example of brining the kafka broker up and consuming a test event.
ENT-8761
Should be used in conjunction with https://github.com/openedx/enterprise-subsidy/pull/243 for testing interservice event pub-sub.
See the additions to the `README` for how to test this locally.
=> build: upgraded deps and local kafka installation

enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py, enterprise_access/apps/api_client/lms_client.py
when fetching group member data with subsidy aggregate data, allowing for the specification of individual learners to be fetched
**Jira:**
https://2u-internal.atlassian.net/browse/ENT-8974
=> feat: allowing for group members to be specified when fetched

enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/api/tests/test_serializers.py, enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/subsidy_access_policy/constants.py, enterprise_access/apps/subsidy_access_policy/models.py
Updates the validation for a policies `spend_limit` where the `spend_limit` may not exceed the `total_deposits`.
The `total_deposits` field from the Subsidy model is the sum of all adjustments and the starting balance.
It will take into account all policies from the the parent `subsidy_uuid`.
The Django Admin screen will display a validation error at the top of the screen if this constraint is violated.
The validation that exists in the `clean()` function on the `SubsidyAccessPolicy` modal only runs if the expected updated `spend_limit` does not equal the current db value of the spend limit. This is done to allow modifications to other fields without running through the specific spend limit logic. This is also done as a precautionary measure for any policies that may …
=> feat: validates spend limit against subsidy balance

enterprise_access/apps/api_client/enterprise_catalog_client.py, enterprise_access/apps/api_client/tests/test_enterprise_catalog_client.py, enterprise_access/apps/enterprise_groups/constants.py, enterprise_access/apps/enterprise_groups/management/commands/groups_reminder_emails.py, enterprise_access/apps/enterprise_groups/management/commands/tests/test_groups_reminder_emails.py, enterprise_access/apps/enterprise_groups/tasks.py, enterprise_access/settings/base.py
We created a cronjob to trigger the management command `groups_reminder_emails` but the command is currently not being recognized. To resolve this, this PR adds `enterprise_access.apps.enterprise_groups` to the `PROJECT_APPS` in order to run the management command `groups_reminder_emails`.
Additionally, this PR adds the `get_catalog_metadata_count` method to retrieve just the catalog count and adds logging. Previously, we were using an existing method `catalog_content_metadata`; however that method requires the `content_keys` param. 
**Jira:**
ENT-9057
https://2u-internal.atlassian.net/browse/ENT-9057
- It may or may not make a migration depending on exactly what you modified, but it should …
=> feat: add enterprise_groups to project apps

enterprise_access/apps/content_assignments/constants.py, enterprise_access/apps/content_assignments/tasks.py, enterprise_access/apps/content_assignments/tests/test_tasks.py
Sends the time in the format `%H:%M` to be parsed by the braze client to the users local time zone. 
It is only updating the task for the assignment reminders to run a stage test on the email campaign with the updated development email template.
**Jira:**
[ENT-8888](https://2u-internal.atlassian.net/browse/ENT-8888)
=> feat: Send action required by time to braze campaign

enterprise_access/apps/content_assignments/tasks.py, enterprise_access/apps/content_assignments/tests/test_tasks.py
Removes `action_required_by` trigger property helper function and usage in favor of `action_required_by_timestamp`.
This is the final step in ensuring a smooth transition between switching attributes used in Braze campaigns.
PRs that added `action_required_by_timestamp`
https://github.com/openedx/enterprise-access/pull/488
https://github.com/openedx/enterprise-access/pull/482
**Jira:**
ENT-8888
=> refactor: Remove usage of `action_required_by`

docker-compose.yml, enterprise_access/apps/subsidy_access_policy/admin/__init__.py
Adding Autocomplete field for Subsidy Access Policy field in Policy Group Association creation form. Note that I did not have to make any changes as laid out in the ticket related to creating access policy screen and hiding it in the left side bar 
In order to provision enterprise-access, I had to bump the memcache version in the docker config to a more recent version, which is included in the changes. 
**Jira:**
[ENT-9059](https://2u-internal.atlassian.net/browse/ENT-9059)
**P**
Autocomplete field:
Filter tests:
1. Filter by UUID:
2. Filter by name:
3. Negative test:
=> Adding Autocomplete field for Subsidy Access Policy field

enterprise_access/settings/base.py, enterprise_access/tasks.py
The changes made to the `max_retries` and `retry_backoff` are in parity with changes in license-manager related tasks.
https://github.com/openedx/license-manager/pull/658
**Jira:**
ENT-9039
=> chore: increase max_retries and retry_backoff for tasks

enterprise_access/apps/subsidy_access_policy/models.py
We're already doing the check of if the user is in the enterprise in a method that we call right after this check. 
**Jira:**
[ENT-9011](https://2u-internal.atlassian.net/browse/ENT-9011)
=> fix: removing redundant group membership check

enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/subsidy_access_policy/models.py
Updates the `spend_limit` constraint check to only check on policies that are active and to determine the sum of the `spend_limit`'s on only active policies.
Also updates how we sum sibling policies in the `total_spend_limit_for_all_policies_associated_to_subsidy` function by using the ORM to determine the sum of siblings and adding together the `spend_limit` in memory. 
**Jira:**
ENT-XXXX
=> fix: filters for only active policies for spend_limit check

enterprise_access/apps/content_assignments/migrations/0021_backfill_allocated_at.py
In the past, we added and started programmatically populating an `allocated_at` field, but it has not yet been backfilled, and we need it to be backfilled in order to use it in features. This commit backfills that field. ENT-9038
An example historical record from local testing:
=> feat: backfill the `LearnerContentAssignment.allocated_at` field

enterprise_access/apps/content_assignments/signals.py
It's not an error if a transaction without a corresponding assignment is reversed, so we should log at INFO level when this happens, rather than at the ERROR level.
=> fix: assignment reversal log info instead of error

enterprise_access/apps/api/v1/tests/test_allocation_view.py, enterprise_access/apps/api/v1/tests/test_assignment_views.py, enterprise_access/apps/content_assignments/models.py, enterprise_access/apps/content_assignments/tests/test_api.py
Helps address
* https://2u-internal.atlassian.net/browse/ENT-9190 (assignment expiration job looks at created instead of allocated_at for many assignments)
Note that we recently backfilled `allocated_at` via a data migration - there should be no assignment records with a null value for this field anymore.
=> fix: prefer allocated_at when determining assignment expiration

enterprise_access/apps/api/v1/tests/test_assignment_views.py, enterprise_access/apps/content_assignments/models.py
This is an easy change since we previously backfilled `allocated_at` and set it to be NOT NULL via
* https://github.com/openedx/enterprise-access/pull/506
* https://github.com/openedx/enterprise-access/pull/509
ENT-9038
=> fix: use allocated_at to determine recent_action time

enterprise_access/settings/production.py
By adding the variable in production, we are making sure that the "next" variable that shows up when an API response is paginated defaults to HTTPS instead of HTTP.
**Jira:**
[ENT-9225](https://2u-internal.atlassian.net/browse/ENT-9225)
=> fix: fixing next property in pagination

enterprise_access/apps/subsidy_access_policy/admin/__init__.py, enterprise_access/apps/subsidy_access_policy/admin/forms.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/test_forced_redemption.py
Add some non-persisted admin model fields for `ForcedPolicyRedemption` so that we can pass along the required GEAG key/value pairs in our forced redeem call. ENT-9137
=> feat: add Exec Ed support for ForcedPolicyRedemption

enterprise_access/apps/subsidy_access_policy/admin/__init__.py, enterprise_access/apps/subsidy_access_policy/tests/test_admin.py
Was missing the email and DSC metadata fields to send to GEAG during forced redemption.
**Jira:**
ENT-9137
=> fix: forced EE redemption needs two additional metadata fields

enterprise_access/apps/subsidy_access_policy/admin/__init__.py, enterprise_access/apps/subsidy_access_policy/tests/test_admin.py
Use a good datetime format for force redeeming with GEAG "terms accepted at".
**Jira:**
ENT-9137
=> fix: send geag terms acceptd at in correct format

enterprise_access/apps/core/apps.py
Easy fix of the only warnings in enterprise-access.
=> refactor: add core.apps file to fix django warnings

requirements/base.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
We had pinned DRF because version 3.15.0 was problematic/non-backwards-compatible. That's been fixed in DRF >= 3.15.1
=> build: unpin DRF and rebuild deps

enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py
include created time in policy api response `api/v1/subsidy-access-policies/?enterprise_customer_uuid=<uuid>`
1. Follow the set up steps here https://github.com/openedx/enterprise-access to get the server running
2. checkout this branch with `git fetch -a` and `git checkout knguyen2/ent-9374`
3. visit http://localhost:18270/admin/  and click on any learner credit to get the customer uuid i.e. http://localhost:18270/admin/subsidy_access_policy/assignedlearnercreditaccesspolicy/22424a81-ddda-4af0-a122-aa32b5d624c9/change/
5. copy the customer uuid and paste in the following link: http://localhost:18270/api/v1/subsidy-access-policies/?enterprise_customer_uuid=<CUSTOMER_UUID>
6. verify that you see the created date
**Jira:**
[ENT-9374](https://2u-internal.atlassian.net/browse/ENT-9374) …
=> feat: include created time in policy api response

enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py, enterprise_access/apps/subsidy_access_policy/constants.py, enterprise_access/apps/subsidy_access_policy/content_metadata_api.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/test_models.py
We want the `can_redeem` query to return false for a given (user, content key)
if the enrollment deadline for the content key is in the past. This is necessary because
some courses have runs with an advertised run for which the deadline is in the future,
but also have available recent runs where the upgrade deadline is in the past.
Depends on https://github.com/openedx/enterprise-catalog/pull/909 and https://github.com/openedx/enterprise-subsidy/pull/286 
A `can_redeem` false payload for a passed enroll by date will have a `reasons` value like this: 
```
"reasons": [
{
"reason": "beyond_enrollment_deadline",
"user_message": "You can't enroll right now because the enrollment deadline for this course has passed.",
"policy_uuids": [
"3cc0ad2c-ede1-476c-8271-97683855e41d"
], …
```
=> feat: can_redeem checks for enrollment deadline

enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py
Supports an optional `lms_user_id` query parameter in the `can-redeem` API to override the default user id used for the request. **Only works if the authenticated request user `is_staff=True`**.
```
http://localhost:18270/api/v1/policy-redemption/enterprise-customer/{enterprise_customer_uuid}/can-redeem/?lms_user_id=1234
```
**Jira:**
[ENT-9291](https://2u-internal.atlassian.net/browse/ENT-9291)
=> feat: allow staff users to override `lms_user_id` in `can-redeem` API

enterprise_access/settings/base.py
Adding Datadog monitoring middleware as per https://docs.google.com/spreadsheets/d/1sh9eE-vT5JysI4BAx_qlkhzZ0hEujM_B18qL4XQoq1k/edit?gid=56476385#gid=56476385
Slack reference: https://twou.slack.com/archives/C0495EETUVC/p1724856564259579
JIRA: [ENT-9422](https://2u-internal.atlassian.net/browse/ENT-9422)
=> Chore: adding Datadog monitoring middleware

enterprise_access/apps/api/serializers/content_assignments/assignment.py, enterprise_access/apps/api/v1/tests/test_assignment_views.py, enterprise_access/apps/content_assignments/models.py, enterprise_access/apps/content_assignments/tasks.py, enterprise_access/apps/content_assignments/tests/test_tasks.py
When the assignment email notification task fails, the corresponding assignment is now NOT moved to an errored state, but instead left in an allocated state. Furthermore, the admin-serializer for the assignment now indicates a "failed" _learner_ state, and an error reason related to the failed notification attempt.
ENT-9037
Here's the new response from the serializer after an assignment was allocated, but the resulting notification task failed:
```
{
"next": null,
"previous": null,
"count": 1,
"num_pages": 1,
"current_page": 1,
"start": 0,
"results": [
{
"uuid": "fdaeb538-2d9d-4875-87ca-2973754ed949",
"assignment_configuration": "a9f97992-4894-4b80-9dde-b08ce3d7bff3",
"learner_email": "test-failed-notification@example.com",
"lms_user_id": null,
"content_key": "edx+DemoX",
"content_title": …
```
=> feat: failed notifications for assignments leave state as allocated

enterprise_access/apps/api/serializers/content_assignments/assignment.py, enterprise_access/apps/api/v1/tests/test_allocation_view.py, enterprise_access/apps/api/v1/tests/test_assignment_views.py, enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api_client/enterprise_catalog_client.py, enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/content_assignments/content_metadata_api.py, enterprise_access/apps/content_assignments/management/commands/automatically_nudge_assignments.py, enterprise_access/apps/content_assignments/management/commands/tests/test_automatically_nudge_assignments.py, enterprise_access/apps/content_assignments/tasks.py, enterprise_access/apps/content_assignments/tests/factories.py, enterprise_access/apps/content_assignments/tests/test_api.py, enterprise_access/utils.py, test_utils/__init__.py
Relying on the update to enterprise-catalog's `get_content_metadata` REST API to return the top-level course object when passing course run key(s) to the `?content_keys` query parameter and the addition of `normalized_metadata_by_run`, this PR updates the `get_content_metadata_for_assignments` method and where it's consumed to support `credits_available`, expiration management commands, and email notifications related to assignments.
**Jira:**
[ENT-8876](https://2u-internal.atlassian.net/browse/ENT-8876)
=> feat: support course run based assignments in credits_available, expiration, emails, etc.

enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/content_assignments/tests/test_api.py, enterprise_access/apps/subsidy_access_policy/constants.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/test_models.py
In `get_assignment_for_learner`, we perform a lookup of assignments based on a top-level course key, even for run-based assignments. Given this, a run-based assignment would never be found. To mitigate, the queryset `get` now considered the assignment's `parent_content_key` as well.
When a learner can redeem with both a `PerLearnerEnrollmentCreditAccessPolicy` _and_ a `AssignedLearnerCreditAccessPolicy`, the `can-redeem` API response does not prioritize the assignment-based policy for redemption over other policy types.
The lack of priority for assignment-based policies was noticed when performing stage QA and observed that the learner portal Course page was suggesting the course was assigned (via a badge and the assignment-specific price messaging), but the redemption was attempting to …
=> feat: support run-based assignments in `can-redeem`; ensure assigned policies have highest priority

.github/workflows/upgrade-python-requirements.yml
This code does not have any dependencies that are specific to any specific
version of ubuntu.  So instead of testing on a specific version and then needing
to do work to keep the versions up-to-date, we switch to the ubuntu-latest
target which should be sufficient for testing purposes.
This work is being done as a part of https://github.com/openedx/platform-roadmap/issues/377
closes https://github.com/openedx/enterprise-access/issues/539
=> build: Switch to ubuntu-latest for builds

enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/content_assignments/management/commands/automatically_nudge_assignments.py, enterprise_access/apps/content_assignments/management/commands/tests/test_automatically_nudge_assignments.py, enterprise_access/apps/content_assignments/tests/factories.py, enterprise_access/apps/content_assignments/tests/test_api.py, enterprise_access/apps/content_assignments/tests/test_tasks.py
Upon assignment re-allocation, ensures the `parent_content_key` and `is_assigned_course_run` fields are updated appropriately.
**Jira:**
[ENT-9522](https://2u-internal.atlassian.net/browse/ENT-9522)
=> fix: update `parent_content_key` and `is_assigned_course_run` on assignment re-allocation

enterprise_access/apps/content_assignments/utils.py
Remove print statements from recently merged PR https://github.com/openedx/enterprise-access/pull/560
**Jira:**
ENT-XXXX
=> fix: remove stray print statements

enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/test_forced_redemption.py
Currently, the forced redemption model persists a course run key to force redeem. It also creates an assignment if in an assignment-based policy. However, it creates the assignment with a course key, and not the run key.
Instead of doing this, we should simply fetch the metadata for the course run key that’s persisted in the forced redemption instance. As long as we get something back, we should just use this persisted value when creating the related assignment record.
**Jira:**
https://2u-internal.atlassian.net/browse/ENT-9562
=> fix: forced assignment redemption assigns course run key

enterprise_access/apps/api_client/base_user.py, enterprise_access/apps/api_client/constants.py, enterprise_access/apps/api_client/license_manager_client.py, enterprise_access/apps/api_client/tests/test_constants.py, enterprise_access/apps/api_client/tests/test_license_manager_client.py, enterprise_access/apps/content_assignments/tests/test_utils.py, enterprise_access/utils.py
Adds license manager api client utilizing the base user client. The `BaseUserClient` is intended to be used in conjuction with the BFF (backend for frontend) layer when making API calls.
Adds API calls to `license_manager_client` which utilizes the new `BaseUserClient`, `LicenseManagerUserApiClient`.
Adds tests for the new set of end points along with data reflective of the serializer from license manager.
**Jira:**
ENT-XXXX
=> feat: add license manager base user client

enterprise_access/apps/api_client/base_user.py, enterprise_access/apps/api_client/license_manager_client.py, enterprise_access/apps/api_client/lms_client.py, enterprise_access/apps/api_client/tests/test_license_manager_client.py, enterprise_access/apps/api_client/tests/test_lms_client.py
1. Adds `LmsUserApiClient`, extending `BaseUserApiClient` to pass-thru the requesting user's JWT token and `X-Request-ID` headers.
2. Implements `get_default_enterprise_enrollment_intentions_learner_status` within `LmsUserApiClient` to fetch the API endpoint introduced via https://github.com/openedx/edx-enterprise/pull/2274.
3. Tests.
**Jira:**
[ENT-9690](https://2u-internal.atlassian.net/browse/ENT-9690)
=> feat: introduce `LmsUserApiClient`, method to fetch enrollment intentions for learner

enterprise_access/apps/bffs/apps.py, enterprise_access/apps/bffs/context.py, enterprise_access/apps/bffs/serializers.py, enterprise_access/apps/bffs/tests/test_context.py, enterprise_access/settings/base.py
This application, bffs, has been added to enterprise-access. bff stands for "backend-for-frontend" and is designed to provide a consolidated API layer for supporting enterprise micro frontends (MFEs). The bffs application serves as an intermediary between frontend components and underlying services, centralizing business logic and data transformation within a single BFF layer. This approach aims to streamline data returned to the frontend, minimizing the need for additional transformation on the client side, and enabling frontend components to consume data in a more ready-to-use format.
Additionally, this PR introduces a HandlerContext component. HandlerContext will store the instantiated requests originating from API client calls, preparing them to be utilized by an …
=> feat: add bff handler context

enterprise_access/apps/api_client/lms_client.py, enterprise_access/apps/api_client/tests/test_lms_client.py
* Adds method to `LmsUserApiClient` to fetch enterprise course enrollments from the `{LMS}/enterprise_learner_portal/api/v1/enterprise_course_enrollment/?enterprise_id={enterprise_uuid}` API endpoint.
**Jira:**
[ENT-9691](https://2u-internal.atlassian.net/browse/ENT-9691)
=> chore: add method to LmsUserApiClient to fetch enterprise enrollments

enterprise_access/apps/bffs/context.py, enterprise_access/apps/bffs/handlers.py, enterprise_access/apps/bffs/tests/test_context.py, enterprise_access/apps/bffs/tests/test_handlers.py
Adds a `BaseHandler` which utilizes the `HandlerContext` responsible for the underlying structure for users of the `BaseHandler`.
Adds the `BaseLearnerPortalHandler` defines respective usable clients and loads data within the `HandlerContext`
It is the orchaestration layer for the MFE responsible for making the API calls and performing transformations. Currently the functions in this class are stubbed out to be completed in future work.
Adds the `DashboardHandler` which retrieves the data from the context to be consumed by the to be added `ResponseBuilder`
Adds MVP tests. The functions and tests will be iterated on specifically on within their separate pieces of work.
**Jira:**
ENT-XXXX
- It …
=> feat: add base and learner portal bff handler

enterprise_access/apps/api_client/lms_client.py, enterprise_access/apps/api_client/tests/test_lms_client.py, enterprise_access/apps/bffs/context.py, enterprise_access/apps/bffs/handlers.py, enterprise_access/apps/bffs/tests/test_context.py, enterprise_access/apps/bffs/tests/test_handlers.py, enterprise_access/apps/bffs/tests/utils.py
**Jira:**
[ENT-9629](https://2u-internal.atlassian.net/browse/ENT-9629)
* Converted additional `HandlerContext` class attributes as private, with `@property` getter functions.
* Refactors `initialize_common_context_data` as `_initialize_common_context_data`:
* Extended to optionally support both `enterprise_customer_uuid` and `enterprise_customer_slug`.
* Extended to include an attribute for `enterprise_features` (returned by `enterprise-learner` API, described below).
* Initializes context `data` with enterprise customer metadata (mostly parity with transforms on the existing Learner Portal request) via the `enterprise-learner` LMS API.
* If no slug/uuid is provided, resolves to the request user's `active=True` enterprise customer user.
* If only slug is provided, finds …
=> feat: initialize enterprise metadata in HandlerContext; complete auto-apply business logic

enterprise_access/apps/api_client/tests/test_license_manager_client.py, enterprise_access/apps/api_client/tests/test_utils.py, enterprise_access/apps/bffs/context.py, enterprise_access/apps/bffs/handlers.py, enterprise_access/apps/bffs/response_builder.py, enterprise_access/apps/bffs/serializers.py, enterprise_access/apps/bffs/tests/test_context.py, enterprise_access/apps/bffs/tests/test_handlers.py, enterprise_access/apps/bffs/tests/test_response_builders.py, enterprise_access/apps/bffs/tests/utils.py
Adds the response builder to the BFF app. The response builders main responsibility is to take the now loaded data from the context layer, and serialize it in preparation to be returned to the user. This includes adding warnings, errors and status codes.
**Jira:**
ENT-XXXX
=> feat: add response builder to the BFF

enterprise_access/apps/bffs/serializers.py
The `MinimalCustomerAgreementSerializer` does not expose the `disable_onboarding_notifications`. It was incorrectly added, and thus removed.
=> fix: remove disable_onboarding_notifications

enterprise_access/apps/api_client/license_manager_client.py, enterprise_access/apps/bffs/handlers.py
In testing on stage, it was observed the revoked licenses were not getting returned by the BFF. This PR ensures they are returned. 
**Jira:**
ENT-XXXX
=> fix: when fetching licenses, return revoked/expired

enterprise_access/apps/api/utils.py, enterprise_access/apps/api/v1/tests/test_bff_views.py, enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/views/bffs/common.py, enterprise_access/apps/api/v1/views/bffs/learner_portal.py, enterprise_access/apps/api_client/tests/test_license_manager_client.py, enterprise_access/apps/api_client/tests/test_utils.py, enterprise_access/apps/bffs/api.py, enterprise_access/apps/bffs/context.py, enterprise_access/apps/bffs/handlers.py, enterprise_access/apps/bffs/response_builder.py, enterprise_access/apps/bffs/serializers.py, enterprise_access/apps/bffs/tests/test_context.py, enterprise_access/apps/bffs/tests/test_handlers.py, enterprise_access/apps/bffs/tests/utils.py, enterprise_access/apps/core/constants.py, enterprise_access/apps/core/rules.py, enterprise_access/settings/base.py
* Adds tests for `LearnerPortalBFFViewSet`.
* Empty state (e.g., new enterprise learner)
* Subscription licenses, including activation and auto-apply
* Enrollments
* Add BFF permissions for viewset with edx-rbac's `@permission_required`.
* Error / exception handling cleanup.
* Adds `get_and_cache_*` methods for `enterprise-learner` and `enterprise-customer` LMS API calls.
* Updated serializers with `allow_null`, etc. where appropriate.
**Jira:**
[ENT-9639](https://2u-internal.atlassian.net/browse/ENT-9639)
=> chore: add tests around BFF viewset; cleanup and minor fixes

enterprise_access/apps/bffs/handlers.py
1. Fix conditional logic.
2. Change check for an activated license to a check for an activate, current license.
=> fix: check for active, current license

enterprise_access/apps/api/v1/tests/test_bff_views.py, enterprise_access/apps/bffs/handlers.py, enterprise_access/apps/bffs/tests/test_handlers.py
* Remove an errant `break` from a loop in `enroll_in_redeemable_default_enterprise_enrollment_intentions()`
* Light refactoring in same function.
* Adds unittests for same function.
**Jira:**
ENT-9632
=> fix: unittests for default realizations, remove errant break

enterprise_access/apps/api/v1/tests/test_bff_views.py, enterprise_access/apps/bffs/api.py, enterprise_access/apps/bffs/context.py, enterprise_access/apps/bffs/handlers.py, enterprise_access/apps/bffs/tests/test_context.py, enterprise_access/apps/bffs/tests/utils.py
Extends auto-apply subscription license business logic and tests to include:
* Check for revoked subscription licenses (i.e., no auto-apply with revoked license).
* Check for being explicitly linked to the requested enterprise customer (i.e., no auto-apply as an unlinked staff user).
These additional checks ensure parity with existing business logic around auto-applied subscription licenses in the frontend ([source](https://github.com/openedx/frontend-app-learner-portal-enterprise/blob/73fc10e94aa64cb9103e8131d3fa9d4031d0c410/src/components/app/data/services/subsidies/subscriptions.js#L184)).
**Jira:**
[ENT-9813](https://2u-internal.atlassian.net/browse/ENT-9813)
- It may or may not make a …
=> fix: account for revoked licenses and staff users in auto-apply logic

enterprise_access/apps/api/v1/views/bffs/common.py, enterprise_access/apps/bffs/context.py, enterprise_access/apps/bffs/handlers.py, enterprise_access/apps/bffs/response_builder.py, enterprise_access/apps/bffs/serializers.py, enterprise_access/apps/bffs/tests/test_context.py, enterprise_access/apps/bffs/tests/test_handlers.py
1. Updates `logger.exception` messages in the BFF.
2. Updates some `user_message` and `developer_message` kwargs when calling `add_error` to add more info e.g., request user's `lms_user_id` and enterprise customer uuid, where possible.
3. Switched one usage of `add_error` to `add_warning` instead, specifically when the BFF response serializer input data is invalid. Rationale: considering it a warning vs. an error since we still resolve a serialized response, just without validation to keep the API response body usable by the frontend.
4. Added some `logger.info` throughout a few places in the BFF for better debugging/observability.
5. Updates `HandlerContext` to expose a `set_status_code` method, used within `add_error` to update the response status code when using …
=> fix: update error handling and add logger.info in BFF

enterprise_access/apps/api/v1/tests/test_bff_views.py, enterprise_access/apps/api_client/tests/test_utils.py, enterprise_access/apps/bffs/serializers.py
Serializes `url_for_button_in_modal_v2` in `CustomerAgreementSerializer`.
**Jira:**
https://2u-internal.atlassian.net/browse/ENT-9837
=> fix: include url_for_button_in_modal_v2 in CustomerAgreementSerializer

enterprise_access/apps/subsidy_access_policy/admin/__init__.py, enterprise_access/apps/subsidy_access_policy/admin/forms.py, enterprise_access/apps/subsidy_access_policy/tests/test_forms.py
**Description:** Add validation on subsidy uuid.
**Jira:** https://2u-internal.atlassian.net/browse/ENT-9800
=> feat: add validation on subsidy uuid

enterprise_access/apps/bffs/api.py, enterprise_access/apps/bffs/tests/test_handlers.py
We don't want to cache default intentions data if it includes any enrollable intentions, because we don't want to re-attempt enrollment realization on the second of consecutive requests.
**Jira:**
ENT-9862
=> fix: don't cache if default intentions need enrollment

requirements/base.in, requirements/base.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
Pins confluent-kafka < 2.7, since we're experiencing increased CPU usage in stage and prod with 2.7.0 installed.
=> build: pin confluent-kafka<2.6.2

docker-compose.yml
ENT-9901
Testing
===
Launching the container:
```
(enterprise-access) ubuntu@ip-10-13-20-242:~/edx-repos/enterprise-access$ make dev.up
...
✔ Container enterprise_access.consume_enterprise_subsidies_transaction_lifecycle  Started                                                                                                                                                                                         0.3s 
```
Container logs after launch:
```
(enterprise-access) ubuntu@ip-10-13-20-242:~/edx-repos/enterprise-access$ make consume_enterprise_subsidies_transaction_lifecycle-logs
...
enterprise_access.consume_enterprise_subsidies_transaction_lifecycle  | 2025-01-10 19:55:14,558 INFO 7 [edx_event_bus_kafka.internal.consumer] [user None] [ip None] [request_id None] consumer.py:284 - …
```
=> test: add local dev container for consuming event-bus events

enterprise_access/apps/api/v1/tests/test_bff_views.py, enterprise_access/apps/bffs/handlers.py, enterprise_access/apps/bffs/mixins.py, enterprise_access/apps/bffs/response_builder.py, enterprise_access/apps/bffs/serializers.py, enterprise_access/apps/bffs/tests/test_handlers.py
Serializes `subscription_license`, `subscription_plan`, and `show_expiration_notifications` within the Learner Portal BFF API, ensuring parity with existing frontend transforms for these same properties.
Corresponding frontend PR: https://github.com/openedx/frontend-app-learner-portal-enterprise/pull/1253
**Jira:**
[ENT-9630](https://2u-internal.atlassian.net/browse/ENT-9630)
=> feat: serialize additional subscriptions-related fields within the Learner BFF

enterprise_access/apps/api/v1/tests/test_bff_views.py, enterprise_access/apps/bffs/constants.py, enterprise_access/apps/bffs/handlers.py, enterprise_access/apps/bffs/mixins.py, enterprise_access/apps/bffs/response_builder.py, enterprise_access/apps/bffs/serializers.py, enterprise_access/apps/bffs/tests/test_handlers.py
Corresponding change in `frontend-app-learner-portal-enterprise`: https://github.com/openedx/frontend-app-learner-portal-enterprise/pull/1293 (**this PR to merge first**)
This PR brings some data transforms from the frontend (frontend-app-learner-portal-enterprise) to the BFF / API Gateway layer, to enable eventually removing business logic from the frontend long-term.
The overall strategy here is to:
1. Expose the additional fields resulting from the transform in the BFF API response (additive-only).
2. Remove the frontend data transforms on the enrollments data served by the BFF API response, relying solely on the BFF transformations.
3. Remove the no-longer consumed (deprecated) fields related to enrollments from the BFF API response.
Other changes:
* Creates …
=> fix: transform and group enrollments by status

enterprise_access/apps/api_client/__init__.py, enterprise_access/apps/api_client/lms_client.py, enterprise_access/apps/api_client/tests/test_lms_client.py, enterprise_access/settings/base.py
In support of https://2u-internal.atlassian.net/browse/ENT-9970
Adds a new API client method to create enterprise customer records.
=> feat: add an LmsApiClient.create_enterprise_customer() method

enterprise_access/apps/api_client/lms_client.py, enterprise_access/apps/api_client/tests/test_lms_client.py
In service of https://2u-internal.atlassian.net/browse/ENT-9970
=> feat: add LmsApiClient.create_enterprise_admin_user() method

enterprise_access/apps/api/v1/tests/test_bff_views.py, enterprise_access/apps/api_client/lms_client.py, enterprise_access/apps/bffs/api.py, enterprise_access/apps/bffs/context.py, enterprise_access/apps/bffs/response_builder.py, enterprise_access/apps/bffs/serializers.py, enterprise_access/apps/bffs/tests/test_context.py, enterprise_access/apps/bffs/tests/test_response_builders.py, enterprise_access/apps/bffs/tests/utils.py
Serializes fields in the BFF context to always return `all_linked_enterprise_customer_users` and `should_update_active_enterprise_customer_user`. The intention is to eventually remove `should_update_active_enterprise_customer_user` and take advantage of a net new API call to select an active enterprise customer. This work will be completed as part of a seperate ticket. 
It modifies the enterprise customer user object to update the metadata to the set active, and invalidate the enterprise customer user query cache. We return `should_update_active_enterprise_customer_user` back to the user to set the active enterprise customer in the frontend. We invalidate the query to ensure the next call to the BFF would return the now active enterprise customer without transformations on the enterprise …
=> feat: incorporate enterprise customer logic into BFF

docs/decisions/0024-provisioning-api.rst, enterprise_access/apps/api/serializers/__init__.py, enterprise_access/apps/api/serializers/provisioning.py, enterprise_access/apps/api/v1/tests/test_provisioning_views.py, enterprise_access/apps/api/v1/urls.py, enterprise_access/apps/api/v1/views/__init__.py, enterprise_access/apps/api/v1/views/provisioning.py, enterprise_access/apps/core/constants.py, enterprise_access/apps/core/rules.py, enterprise_access/settings/base.py, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
https://2u-internal.atlassian.net/browse/ENT-9970
1. Ensure your requesting user is either a superuser or has the `enterprise_provisioning_admin` role assigned via edxapp: http://localhost:18000/admin/enterprise/systemwideenterpriseuserroleassignment/add/
2. Make POST request to `http://localhost:18270/api/v1/provisioning` with body like 
```
{
"enterprise_customer": {
"name": "Test customer",
"country": "US",
"slug": "test-customer"
},
"pending_admins": [
{
"user_email": "test-admin@example.com"
}
]
}
```
3. Observe `ack` response.
=> feat: provisioning api skeleton

enterprise_access/settings/base.py
- PR created under the issue https://github.com/edx/edx-arch-experiments/issues/815
- `edx_django_utils.monitoring.middleware.MonitoringCustomMetricsMiddleware` has been deprecated for a while and has been replaced with `edx_django_utils.monitoring.CachedCustomMonitoringMiddleware`
=> refactor: update deprecated MonitoringCustomMetricsMiddleware

enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py, enterprise_access/apps/api_client/enterprise_catalog_client.py, enterprise_access/apps/api_client/tests/test_enterprise_catalog_client.py, enterprise_access/apps/content_metadata/api.py, enterprise_access/apps/content_metadata/tests/test_api.py, enterprise_access/apps/subsidy_access_policy/content_metadata_api.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/subsidy_api.py, enterprise_access/apps/subsidy_access_policy/tests/test_content_metadata_api.py, enterprise_access/apps/subsidy_access_policy/tests/test_subsidy_api.py
This basically adds a fallback branch when calculating the list_price to serialize into the can-redeem endpoint.  The fallback logic relies on a net new call to enterprise-catalog to fetch content metadata containing price information agnostic of any catalog or customer.
ENT-9660
Local Dev Testing
===
For this manual test, I created an learner credit plan with only an assignable budget, but no assignments.
```
GET /api/v1/policy-redemption/enterprise-customer/298629a4-0fbf-44db-bcfb-9c604eca0bc8/can-redeem/?content_key=course-v1%3AedX%2BDemoX%2BDemo_Course
```
<details>
<summary>can-redeem response BEFORE commit has null list_price</summary>
```json
[
{
"content_key": "course-v1:edX+DemoX+Demo_Course",
"list_price": null,
"redemptions": [],
"has_successful_redemption": false, …
```
=> feat: list_price is always populated in can_redeem

enterprise_access/apps/subsidy_access_policy/content_metadata_api.py, enterprise_access/apps/subsidy_access_policy/tests/test_content_metadata_api.py
This should hopefully surface buggy inputs before they get harder to track as they get passed along.
ENT-9660
=> feat: protect against decimal cents.

requirements/constraints.txt
ENT-10153
pinning braze-client below version 1, which will likely introduce a breaking-change
as the package is converted to an openedx plugin.
see https://github.com/edx/braze-client/pull/30
=> build: pin edx-braze-client<1

enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py
A bug ticket came through on-call that surfaced a bug when the course_price is 0. With this line of code, if the first check of the OR condition evaluated to 0.0 it would read as falsy even though this is a valid imput, which would automatically set the decimal_dollars value to whatever the second check was, which in this case was None which resulted in us throwing an exception. 
```
decimal_dollars = (
course_metadata['normalized_metadata_by_run'].get(content_key, {}).get('content_price') or
course_metadata['normalized_metadata'].get('content_price')
)
```
**Jira:**
[ENT-10180
](https://2u-internal.atlassian.net/browse/ENT-10180)
- It may or may not make a migration depending on exactly what …
=> fix: bug fix for can_redeem course_price

enterprise_access/apps/api/v1/tests/test_bff_views.py, enterprise_access/apps/api/v1/views/bffs/common.py, enterprise_access/apps/api/v1/views/bffs/learner_portal.py, enterprise_access/apps/bffs/handlers.py, enterprise_access/apps/bffs/response_builder.py, enterprise_access/apps/bffs/serializers.py, enterprise_access/apps/bffs/tests/test_response_builders.py, enterprise_access/apps/bffs/tests/utils.py, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip.txt, requirements/production.txt, requirements/quality.txt, requirements/test.in, requirements/test.txt, requirements/validation.txt
* Refactors `BaseResponseBuilder` and `load_route_data_and_build_response` a bit to abstract some generic/re-usable logic to be common across all BFF API endpoints for any given page route, making it easier and more straightforward to create a new BFF API endpoint.
* tl;dr; Each response builder subclass (e.g., `LearnerDashboardResponseBuilder`) must define a `serializer_class` attr for that page route's specific serializer but the actual serialization of the data itself is handled within `BaseResponseBuilder`'s newly added `serialize` method.
* Exposes additional BFF API endpoints for the following page routes in Learner Portal. Each of these API endpoints only contain the common data exposed across all page routes within the Learner Portal BFF. Route-specific data may be incrementally …
=> feat: expose base BFF APIs for search, academy, and skills quiz routes

enterprise_access/apps/api/v1/tests/test_bff_views.py, enterprise_access/apps/bffs/handlers.py, enterprise_access/apps/bffs/tests/test_handlers.py, enterprise_access/apps/bffs/tests/utils.py
Adjust the display logic for the Integration Warning modal in the Learner Portal. Previously, the modal displayed when search was enabled and an identity provider was configured. This resulted in confusion for customers who did not have an LMS integration but saw the modal due to having SSO enabled.
Changes:
- Update the condition to display the Integration Warning modal only if the enterprise customer has an active LMS integration.
- Use the active_integrations field from the BFF or direct LMS API call as the new condition.
- Ensure customers without LMS integrations do not see the modal, regardless of SSO setup.
**Jira:**
[ENT-10068 - IntegrationWarning showing for a customer with search enabled and no identity …
=> fix: update integration warning logic to check active LMS integrations

enterprise_access/apps/api/v1/tests/test_bff_views.py, enterprise_access/apps/api_client/enterprise_catalog_client.py, enterprise_access/apps/api_client/tests/test_enterprise_catalog_client.py, enterprise_access/apps/bffs/api.py, enterprise_access/apps/bffs/context.py, enterprise_access/apps/bffs/response_builder.py, enterprise_access/apps/bffs/serializers.py, enterprise_access/apps/bffs/tests/test_context.py, enterprise_access/apps/bffs/tests/test_handlers.py, enterprise_access/apps/bffs/tests/test_response_builders.py, enterprise_access/apps/bffs/tests/utils.py, enterprise_access/utils.py
Adds the algolia secured api key response from enterprise catalog to the root BFF response. This involves updating the serializer, context and response builder.
**Jira:**
[ENT-10085](https://2u-internal.atlassian.net/browse/ENT-10085)
=> feat: integrate algolia api keys into the bff base response

enterprise_access/apps/admin_portal_learner_profile/serializers.py, enterprise_access/apps/api/v1/tests/test_admin_portal_learner_profile.py
Fixes a bug where the Learner Portal endpoint does not return error messages in the expected format.
**Important:**
The code was generated with some help of AI, which was reviewed by me. However the review here should also have extra scrutiny that there's no weirdness in the code.
**Jira:**
[ENT-10214](https://2u-internal.atlassian.net/browse/ENT-10214)
**How to test:**
1. test that existing API response has not been broken
- Grab a suitable enterprise customer and learner
- Go to /api-docs/
- Execute the /v1/admin-view/learner_profile/ endpoint with the required arguments
- Make sure expected results are returned
2. test that error response is now as expected
- Fabricate HTTP errors when the `EnterpriseAccess` code requests subscriptions, group memberships, and …
=> fix: learner profile error response

enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/urls.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py
When a group is deleted, we want to have a post-delete signal that calls this endpoint to delete all PolicyGroupAssociations that have the group_uuid associated with it. 
**Jira:**
[ENT-9904
](https://2u-internal.atlassian.net/browse/ENT-9904)
**Testing instructions:**
- Prereqs: Have existing EnterpriseCustomer 
- Create [EnterpriseGroup](http://localhost:18000/admin/enterprise/enterprisegroup/) in lms
- Create a [Policy](http://localhost:18270/admin/subsidy_access_policy/perlearnerenrollmentcreditaccesspolicy/) in enterprise-access
- Create a [PolicyGroupAssociation](http://localhost:18270/admin/subsidy_access_policy/policygroupassociation/) in enterprise-access
- Navigate to enterprise-access [api page](http://localhost:18270/api-docs/) and find the …
=> feat: adding endpoint to delete PolicyGroupAssociation

enterprise_access/settings/base.py, enterprise_access/settings/local.py, enterprise_access/settings/production.py, enterprise_access/settings/utils.py
As part of ENT-10092 to correlate logs with DataDog traces, we need the ability to add trace/span IDs to the log lines. However, this being an open source project, we cannot assume a particular format and observability tool. Hence the need to allow operators to completely override the log format.
ENT-10092
Context
===
This approach borrows from the one implemented for credentials last year:
* https://github.com/openedx/credentials/pull/2660
* https://github.com/openedx/credentials/pull/2658
* https://github.com/openedx/credentials/pull/2644
=> feat: allow logging format to be overridden

enterprise_access/apps/api_client/license_manager_client.py, enterprise_access/apps/api_client/lms_client.py, enterprise_access/apps/api_client/tests/test_license_manager_client.py, enterprise_access/apps/api_client/tests/test_lms_client.py, enterprise_access/settings/base.py
ENT-10004
License-manager client methods to get/create customer agreements, and create subscription plans.
=> feat: client methods to create customer agreement and subs plan

enterprise_access/settings/production.py
This will allow certain environment-specific headers (such as Datadog-specific headers) to be allowed without polluting this generic codebase.
ENT-9625
=> feat: Support injection of extra allowed headers

enterprise_access/apps/content_assignments/tasks.py, enterprise_access/apps/content_assignments/tests/test_utils.py, enterprise_access/apps/content_assignments/utils.py, enterprise_access/utils.py
Emails to learners about course assignments previously displayed the current date as the course "start date" in this case:
* course is self-paced.
* end date is far enough in the future that there's enough time to complete.
* start date is in the future.
Displaying the current date rather than the actual course start date in this specific case was unintentional, and does not match the corresponding logic in the learner-portal.
ENT-10263
=> fix: [assignment email] show actual course start date for courses which have not started

enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/subsidy_access_policy/admin/__init__.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/test_forced_redemption.py
This fixes a problem with forced redemption, where we can't create assignments for some lms user ids because the user has never auth'd into enterprise-access (typically because they're new, or have never visited the learner portal). The fix switches the lookup of user email (based on lms user id) to the `LmsApiClient()` instead of the `core.User` model.
This also required the addition of an optional kwarg to `allocate_assignments()`, which allows us to skip the mapping of lms user id <-> email if the caller already knows the lms user id(s) of the learner emails being allocated (which the forced redemption flow will always know).
Additionally, makes the django admin UI much more friendly and usable.
**Jira:**
TODO
- *Note*: This **must** be run if you …
=> fix: forced redemption assignment email lookup

enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/test_forced_redemption.py, enterprise_access/apps/subsidy_request/models.py
We have to account for email inputs with uppercase characters in the forced redemption `known_lms_user_ids` use case.
**Jira:**
ENT-10385
=> fix: account for casing in forced redemption

enterprise_access/apps/content_assignments/management/commands/automatically_nudge_assignments.py
Currently the `automatically_nudge_assignments` job queries content metadata in batches of 100 from `enterprise-catalog`.  This has begun to fail recently because the list of course keys used to query has exceeded the maximum length of a url.  This change makes the batch size configurable, with a conservative default batch size.
**Jira:**
[ENT-10403](https://2u-internal.atlassian.net/browse/ENT-10403)
=> feat: configurable automatically_nudge_assignments batch size

enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_request/models.py
I removed "skip-all" from a couple of files in a previous commit. The linter ran fine locally for me, but continues to crash in github actions for reasons unknown.
=> fix: skip pylint checking on some models files

enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api/v1/views/subsidy_access_policy.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/test_models.py, enterprise_access/apps/subsidy_access_policy/tests/test_utils.py, enterprise_access/apps/subsidy_access_policy/utils.py
Exposes a net new field from the `SubsidyAccessPolicyCanRedeemElementResponseSerializer`, `display_reason`. The intent of this new field is to isolate a failed redemption reason to the client without naively picking the zero indexed value. 
The logic within `evaluate_policies` was also updated to bring sorting logic implemented downstream, higher in the call stack to correctly sort policies for both redeemable and non-redeemable policies.
Can-redeem response:
**Jira:**
[ENT-10268](https://2u-internal.atlassian.net/browse/ENT-10268)
=> feat: expose `display_reason` derived from `reasons`

enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py, enterprise_access/apps/api_client/lms_client.py, enterprise_access/apps/enterprise_groups/management/commands/groups_reminder_emails.py
Ensures the `get_pending_enterprise_group_memberships` method in `LmsApiClient` returns an empty list vs. `None` to prevent attempting to iterate over `None` in downstream code paths.
**Jira:**
[ENT-10474](https://2u-internal.atlassian.net/browse/ENT-10474)
=> fix: ensure `get_pending_enterprise_group_memberships` always returns a list

enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/api/serializers/subsidy_requests.py, enterprise_access/apps/api/v1/tests/test_subsidy_access_policy_views.py
The `queryset` argument in the `assignment` field of the `LearnerCreditRequestSerializer` was set as a string. This caused an `AttributeError` during API schema generation, preventing the Redoc site from working properly. This commit updates the serializer to use the correct `QuerySet` object, resolving the error.
**Jira:**
[ENT-10463 - [enterprise-access] Redoc site not working](https://2u-internal.atlassian.net/browse/ENT-10463)
=> fix: updated LearnerCreditRequestSerializer to resolve schema generation error

enterprise_access/apps/subsidy_request/admin.py
This PR updates the Django admin interface for the LearnerCreditRequest model.
The changes ensure that most fields are now editable in the admin form. uuid remains read-only. The get_course_partners field also remains read-only as it's a display method for formatted data, not a directly editable model field. 
**Jira:**
ENT-XXXX
=> feat: make LearnerCreditRequest fields editable in django admin

enterprise_access/apps/api_client/license_manager_client.py, enterprise_access/apps/api_client/tests/test_license_manager_client.py
The `learner-licenses` API request to `license-manager` currently does not pass a `page_size` query param; it seems the API itself is only paginating with 10 rows per page, despite the base `PAGE_SIZE` param in the `license-manager` settings appearing to be 100 already.
Either way, we are opting to explicitly pass a `?page_size=` query param in both the BFF API layer _and_ Learner Portal ([PR](https://github.com/openedx/frontend-app-learner-portal-enterprise/pull/1374)) for parity.
**Jira:**
TBD
=> fix: pass page_size query param to learner-licenses API

enterprise_access/apps/api/serializers/provisioning.py, enterprise_access/settings/base.py
https://2u-internal.atlassian.net/browse/ENT-10519
* expose the valid product_id choices in API docs/serailizer.
* add help text to clarify where sf_opp_line_item should be drawn from.
* customer_agreement should be an optional object in the payload (with optional fields inside)
* expose valid catalog_query_id field in API docs/serializer.
=> fix: better serializer and API docs for provisioning

enterprise_access/apps/api/serializers/provisioning.py, enterprise_access/apps/api/v1/tests/test_provisioning_views.py, enterprise_access/apps/api/v1/views/provisioning.py, enterprise_access/apps/provisioning/models.py, enterprise_access/settings/base.py, enterprise_access/settings/test.py
The called of the subscription provisioning API is not required to specify the enterprise catalog record desired. If none is provided, we infer the catalog title based on a simple format, and infer the catalog query id based on the requested subscription plan product_id, which field *is* required. 
**Jira:**
ENT-10519
=> feat: optional catalog input during provisioning

enterprise_access/apps/customer_billing/api.py, enterprise_access/apps/customer_billing/tests/test_api.py
Leave detailed comment in case we change our minds and want to revisit redirect-based payment methods.
=> fix: return_url is likely not needed for MVP

enterprise_access/apps/api/serializers/__init__.py, enterprise_access/apps/api/serializers/subsidy_requests.py, enterprise_access/apps/api/v1/tests/test_browse_and_request_views.py, enterprise_access/apps/api/v1/views/browse_and_request.py, enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/content_assignments/tests/test_api.py, enterprise_access/apps/subsidy_access_policy/api.py, enterprise_access/apps/subsidy_access_policy/constants.py, enterprise_access/apps/subsidy_access_policy/exceptions.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/test_api.py, enterprise_access/apps/subsidy_access_policy/tests/test_models.py, enterprise_access/apps/subsidy_request/tests/factories.py
This PR introduces an API endpoint to approve a Learner Credit Request, which will be invoked from the Admin Portal when an admin approves a request.
**Implementation details:**
- Validates whether a request can be approved using the existing "can_allocate" functionality.
- Allocates a content assignment to the learner using existing logic.
- Associates the assignment with the learner credit request.
- Updates the request’s status to APPROVED.
- Logs the action in the LearnerCreditRequestActions model for auditing purposes.
**Jira:**
https://2u-internal.atlassian.net/browse/ENT-10347  …
=> feat: API to Approve Learner Credit Request

enterprise_access/apps/api/serializers/__init__.py, enterprise_access/apps/api/serializers/subsidy_requests.py, enterprise_access/apps/api/v1/tests/test_browse_and_request_views.py, enterprise_access/apps/api/v1/views/browse_and_request.py, enterprise_access/apps/content_assignments/api.py, enterprise_access/apps/subsidy_request/models.py, enterprise_access/apps/subsidy_request/tests/test_models.py
Created the cancel api for learner credit request. It uses the existing `cancel_assignments` function to cancel the associated assignment and then updates the request state.
**Jira:**
[ENT-10357](https://2u-internal.atlassian.net/browse/ENT-10357)
=> feat: added cancel api endpoint for learner credit request

enterprise_access/apps/api/serializers/subsidy_access_policy.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/test_models.py
Added two methods `total_allocated` and `spend_available` for PerLearnerCreditAccessPolicy to return utilization details.
**Jira:**
[ENT-10338](https://2u-internal.atlassian.net/browse/ENT-10338)
=> feat: add utilization detail methods for PerLearnerSpentCreditAccessPolicy

enterprise_access/apps/customer_billing/pricing_api.py, enterprise_access/apps/customer_billing/tests/test_pricing_api.py, enterprise_access/settings/base.py, enterprise_access/settings/devstack.py
Implements a central Python API for fetching and serializing Stripe pricing data to support the self-service purchasing. The API provides functions to fetch individual or multiple price records with TieredCache caching, serialize them in a basic format matching existing Learner Credit APIs, and includes utility functions for subtotal calculations and price display formatting. Schema validation ensures Stripe responses match expected structure, and comprehensive TypedDict definitions provide type safety and documentation for the serialized data format.
**How to test** 
Settings in private.py:
```python
STRIPE_API_KEY = '[STORED IN PASSWORD MANAGER or Stripe dashboard]'
SSP_PRODUCTS = {
'find a product with a price': {
'stripe_price_id': 'price_1234',
'quantity_range': (0, …
```
=> feat: stripe pricing API integration

enterprise_access/apps/subsidy_access_policy/models.py
Modified the `credits_available` model method for `PerLearnerSpendCreditAccessPolicy` to return True is BnR is enabled and per learner spent limit is set to 0.
**Jira:**
[ENT-10641](https://2u-internal.atlassian.net/browse/ENT-10641?atlOrigin=eyJpIjoiOTIzM2E1M2VmNzk0NDhmZWE4ZDIwYWY4ZTEwNjRmNDEiLCJwIjoiaiJ9)
=> fix: credits_available endpoint should return BnR policy if per learner spent limit is 0

enterprise_access/apps/api/v1/tests/test_checkout_bff_views.py, enterprise_access/apps/bffs/checkout/context.py, enterprise_access/apps/bffs/checkout/handlers.py, enterprise_access/apps/bffs/checkout/response_builder.py, enterprise_access/apps/bffs/checkout/serializers.py, enterprise_access/apps/bffs/handlers.py, enterprise_access/apps/bffs/tests/test_checkout_handlers.py, enterprise_access/apps/bffs/tests/test_checkout_response_builder.py, enterprise_access/apps/customer_billing/constants.py, enterprise_access/apps/customer_billing/models.py
ENT-10700 | CheckoutIntent state needs to be surfaced to the frontend in order to give real-time feedback to the "go to dashboard" stateful button, conditionally perform a forced redirect from other pages to the success page, and support a hard refresh of the Success page.
This change adds a minimal CI serializer to the checkout context BFF response.
https://2u-internal.atlassian.net/browse/ENT-10700
API docs:
http://localhost:18270/api/schema/redoc/#tag/Checkout-BFF/operation/checkout_context
=> feat: Minimal CheckoutIntent serializer

enterprise_access/apps/api/v1/tests/test_checkout_intent_views.py, enterprise_access/apps/customer_billing/constants.py
Small fix from a conversation earlier this week: CheckoutIntents in the `ERRORED_PROVISIONING` state should only be allowed to move into `FULFILLED` - moving into `PAID` is actually moving "backwards".
=> fix: CI state errored provisioning -> fulfilled

enterprise_access/apps/subsidy_access_policy/admin/__init__.py, enterprise_access/apps/subsidy_access_policy/admin/forms.py, enterprise_access/apps/subsidy_access_policy/constants.py, enterprise_access/apps/subsidy_access_policy/models.py, enterprise_access/apps/subsidy_access_policy/tests/test_models.py
In cases where the external fulfillment already exists (Order UUID already exists for an existing GEAG allocation), allow the ID to be specified in the ForcePolicyRedemption form and annotate the transaction to give enterprise-subsidy redemption logic a fallback value to use.
ENT-10879
Related PR: https://github.com/openedx/enterprise-subsidy/pull/389
UI Screenshot
---
=> feat: [ForcedPolicyRedemption] Provide external reference ID fallback

enterprise_access/apps/subsidy_access_policy/models.py
The approach actually used was to pass the UUID via transaction metadata, not as a net-new `create_subsidy_transaction()` kwarg. If you follow this kwarg into the [client function code](https://github.com/openedx/edx-enterprise-subsidy-client/blob/8a6579b96abf4e927181fc17b9b1fb8b1aa56005/edx_enterprise_subsidy_client/client.py#L231-L239), it actually doesn't have a matching kwarg, and would throw an "unexpected keyword argument" error if actually passed.
Relevant: https://github.com/openedx/enterprise-access/pull/833/files#r2328422191
=> fix: remove dead code accidentally left after refactor

enterprise_access/apps/api/v1/views/customer_billing.py, enterprise_access/apps/customer_billing/models.py, enterprise_access/apps/customer_billing/tests/test_models.py
* model-level state transitions actually respect the allowed state transitions defined in constants.py.
* CheckoutIntent state transitions now always log when they happen.
=> feat: tighten up CheckoutIntent state transitions

enterprise_access/apps/api/filters/subsidy_request.py, enterprise_access/apps/api/tests/test_serializers.py, enterprise_access/apps/api/v1/views/browse_and_request.py, enterprise_access/apps/subsidy_request/models.py
- Add learner_request_state and learner_request_state__in filters
- Support filtering by computed states like 'waiting' and 'failed'
- Include help text with all available state values
**Jira:**
ENT-XXXX
=> fix: add learner_request_state filter to learner credit requests

enterprise_access/settings/base.py
Continuation of this ticket, which provided permissions to view a learner detail page from admin-portal, but did not give those permissions to people with the edx-operator role, so some internal staff were having trouble viewing it. This PR retains admin access but given to operators as well. 
**Jira:**
[ENT-10917
](https://2u-internal.atlassian.net/browse/ENT-10917)
=> fix: adding learner profile permissions to operators

enterprise_access/apps/api_client/lms_client.py, enterprise_access/apps/api_client/tests/test_lms_client.py
SSP Teams plans should be provisioned with enable_analytics_screen=False by default.
**Jira:**
[ENT-10727](https://2u-internal.atlassian.net/browse/ENT-10727)
=> feat: SSP Teams plans should be provisioned with enable_analytics_screen=False

enterprise_access/apps/customer_billing/models.py, enterprise_access/apps/customer_billing/tests/test_models.py
This pull request makes a small but important fix to the formatting of the admin portal URL for fulfilled checkout intents, ensuring a slash is present between the base URL and the enterprise slug. It also updates the related test to match the new URL formatting.
See the [prod and stage](https://github.com/search?q=repo%3Aedx%2Fedx-internal%20ENTERPRISE_ADMIN_PORTAL_URL&type=code) config files for validation. 
- URL formatting fix:
* Updated the `admin_portal_url` property in `customer_billing/models.py` to include a slash (`/`) between `ENTERPRISE_ADMIN_PORTAL_URL` and `enterprise_slug`, ensuring correct URL construction.
- Test update:
* Modified the test in `test_models.py` to use the base URL without a trailing slash, aligning the test with the new URL formatting …
=> fix: add forward slash between slug and url for admin portal url
